"""Knowledge pack: forex (currency) trading in depth.

Mechanics (pips, lots, margin, swap), market structure (sessions, dealers,
brokers, regulators), macro drivers (rates, PPP, dollar smile, risk appetite),
the strategies retail and systematic traders actually run, and the honest
record of where each one fails.
"""

from __future__ import annotations

DOMAIN = "Forex and currency trading"

LESSONS: list[tuple[str, str]] = [
    ("Pips, lots and pip value", "A pip is the fourth decimal (0.0001) for most currency pairs and the second decimal (0.01) for yen pairs; brokers quote a fifth digit called a pipette. A standard lot is 100,000 units of the base currency, a mini lot 10,000 and a micro lot 1,000. Pip value equals lot size times pip size, denominated in the quote currency: one standard lot of EURUSD moves 10 dollars per pip, a mini lot 1 dollar, a micro lot 10 cents. For USDJPY a standard lot moves 1,000 yen per pip, roughly 6.7 dollars at 150, so yen pairs need conversion into the account currency. Getting pip value wrong is the most common reason a position sizing calculation is off by a factor of ten. Every stop loss and risk figure in forex is built on this arithmetic."),
    ("Margin and leverage math", "Margin is the collateral a broker locks for a position: notional divided by leverage. One standard lot of EURUSD at 1.10 is 110,000 dollars of notional, so 30:1 leverage requires about 3,667 dollars and 50:1 about 2,200. Effective leverage is notional divided by equity, not the broker's maximum: a 10,000 dollar account holding one standard lot runs 11:1, so a 1% move in the pair changes equity by 11%. Margin level is equity divided by used margin; most brokers close positions when it falls to 50% (ESMA mandates this close-out), which arrives fast at high leverage. Leverage does not create edge, it only scales volatility and the speed of ruin, so size positions from stop distance and risk per trade, then check that margin is comfortably sufficient."),
    ("Majors, minors and exotics", "The seven majors pair the dollar with EUR, JPY, GBP, CHF, AUD, CAD and NZD; the dollar is on one side of roughly 89% of all forex turnover, and EURUSD alone is over a fifth of it. Minors or crosses like EURGBP, EURJPY, GBPJPY and AUDNZD exclude the dollar and are synthesized by dealers from two dollar legs, which is why their spreads are wider. Exotics pair a major with an emerging currency such as USDTRY, USDZAR or USDMXN. Retail spreads scale with liquidity: EURUSD 0.1 to 1 pip, GBPJPY 2 to 4 pips, exotics 20 to 100 pips plus large swap charges. Because transaction costs are proportionally huge in exotics, short-term strategies that look fine on EURUSD are usually unprofitable there."),
    ("Trading sessions and liquidity by hour", "Forex runs continuously from Sunday evening to Friday evening New York time, but liquidity moves with the sun. Sydney opens around 22:00 UTC, Tokyo at 00:00, London at 07:00 or 08:00 depending on daylight saving, New York at 13:00, and the market effectively closes at 22:00 UTC Friday. The BIS survey shows the United Kingdom handles about 38% of turnover and the United States around 19%, so European and American hours carry most volume and the tightest spreads. The Asian session is quiet for EUR and GBP pairs but active for JPY, AUD and NZD. Hourly average true range for EURUSD is often three times larger at 13:00 UTC than at 03:00 UTC, which is why session filters change a strategy's results more than most indicators."),
    ("The London open and the New York overlap", "The London open near 08:00 local time brings the largest single injection of liquidity, often setting the day's direction for European pairs, and the London-New York overlap from 13:00 to 16:00 or 17:00 UTC is the highest-volume window in the market. Spreads are tightest, slippage lowest and most macro data arrives here, including US releases at 08:30 Eastern. Around 16:00 London the WM/Reuters benchmark fix concentrates real-money flows, and month-end fixes can move pairs 30 to 50 pips in minutes. Traders exploit the overlap for breakout and momentum strategies and avoid the post-New York afternoon, when volume dries up and ranges shrink. The catch is that everyone knows this, so the London open also hosts the most stop hunts and false breakouts."),
    ("Swap and rollover mechanics", "Spot forex settles in two days, so a position held past the daily rollover at 17:00 New York time is rolled forward and charged or credited the overnight interest differential, called swap or tom-next. Long the higher-yielding currency earns swap; long the lower-yielding one pays it. Wednesday rollover charges three days to cover the weekend settlement, which is why swing traders time entries around it. Brokers add a markup, so both sides of a pair are often negative in practice and the credit is smaller than the raw interest rate differential. As a rough check, swap per day on 100,000 units is notional times the differential minus markup, divided by 365: a 3.5% net differential on 65,000 dollars of AUDJPY notional is about 6 dollars per day. Ignoring swap quietly bleeds any strategy that holds for weeks."),
    ("Carry trade math and its crash risk", "A carry trade is long a high interest rate currency funded in a low one; its expected return is the interest rate differential, its risk is the spot move. Forward prices already embed that differential through covered interest parity, so the trade is really a bet that spot will not depreciate as much as the forward implies, known as the forward premium puzzle. Diversified G10 carry earned a Sharpe ratio near 0.5 to 0.8 over decades with strong negative skew: AUDJPY fell about 40% in the second half of 2008, and in August 2024 USDJPY dropped from 162 to 142 in three weeks as leveraged yen shorts unwound. A 5% annual differential is about 0.02% per day against daily volatility near 0.7%, so one bad day erases months of carry; position sizing and volatility filters matter more than the yield."),
    ("Interest rate differentials and central bank divergence", "Currencies move on changes in expected interest rates, not on the rate level itself. Traders watch two-year yield spreads and overnight index swap curves, which price the path of policy; a pair reprices when data shifts that path. Divergence trades pair a hiking central bank against one on hold: the Federal Reserve hiking 425 basis points in 2022 while the Bank of Japan stayed at minus 0.1% drove USDJPY from 115 to 151. The trade fails when expectations are already priced, when risk-off flows override rates, or when intervention caps the move. The practical rule is to compare the market-implied path with your own view and only trade the gap; buying a currency because its rate is high is the carry trade, not the differential trade."),
    ("Purchasing power parity and long-run fair value", "Purchasing power parity says exchange rates should equalize the price of a basket of goods across countries; the Big Mac index and OECD PPP estimates are the common versions. Deviations are large and persistent, with an estimated half-life of three to five years, so PPP is nearly useless for timing but informative over multi-year horizons: currencies more than 20 to 30% from fair value tend to drift back. The real effective exchange rate, adjusted for inflation and trade weights, is the practical valuation metric. Productivity differences and terms of trade shift fair value itself, which is why the Swiss franc and the yen can sit far from PPP for a decade. Use it as a slow tilt for position sizing, never as a stop loss substitute."),
    ("The dollar smile", "The dollar smile, credited to Stephen Jen, says the dollar rallies at both extremes: when the US economy outperforms and the Federal Reserve is tightening, and when global risk collapses and investors scramble for dollar liquidity. It weakens in the middle, when global growth is strong and synchronized and capital flows to higher-beta currencies and emerging markets. In March 2020 the dollar index jumped about 8% in ten days despite emergency rate cuts, the crisis side of the smile. The dollar index itself is 57.6% euro, 13.6% yen, 11.9% sterling, 9.1% Canadian dollar, plus krona and franc, so it is mostly a EURUSD mirror. The theory frames regime, not timing: identifying which side of the smile the market is on tells a trader whether rate differentials or risk appetite is driving flows."),
    ("Risk-on and risk-off currencies", "In risk-off episodes the yen, Swiss franc and dollar strengthen while the Australian and New Zealand dollars, the Canadian dollar and emerging market currencies fall. The yen and franc are safe havens because Japan and Switzerland are large net creditors with low interest rates, so they fund carry trades that get unwound in panics; AUDJPY often tracks the S&P 500 closely and serves as a risk barometer. The relationship is not fixed: in 2022 the yen fell hard during a bear market because rate differentials, not risk, dominated. Traders use the split to hedge: a long commodity currency position with a long yen leg has lower drawdown in crashes. The failure mode is treating the correlations as constant, when rolling three-month correlations swing between 0.3 and 0.9."),
    ("Commodity currencies", "The Canadian dollar, Australian dollar, New Zealand dollar and Norwegian krone are commodity currencies because exports drive their terms of trade. USDCAD has moved inversely with crude oil, with rolling correlations to WTI often between minus 0.5 and minus 0.8; AUDUSD follows iron ore, copper and Chinese demand; NZD tracks dairy prices; NOK tracks Brent; the Chilean peso tracks copper and the rand tracks gold and platinum. Traders use the commodity as a leading fundamental input and trade the currency when it lags, or hedge a commodity position with the currency. The link breaks when interest rate differentials dominate, as in 2022 when oil was high but CAD weakened against a surging dollar, and it weakens as economies diversify, so estimate the correlation on recent data before relying on it."),
    ("Emerging market currencies and crisis dynamics", "Emerging market currencies offer high carry and fat left tails. Countries with current account deficits, dollar-denominated debt and shallow reserves are vulnerable to sudden stops, when foreign capital leaves and the currency gaps lower: the Turkish lira lost about 40% in 2018 and again in 2021, the Argentine peso repeatedly, and Asian currencies in 1997. During stress, spreads widen tenfold, forwards trade as non-deliverable contracts, and capital controls can freeze positions. Retail brokers charge large swaps and may halt trading in exotics. The liquidity premium that pays in calm months is compensation for these events, so size EM positions at a fraction of major-pair size and treat weekend gaps as a real cost. Trend following on EM pairs has captured crisis moves better than carry or mean reversion."),
    ("Central bank intervention", "Central banks intervene by selling or buying their own currency, or by talking it down or up. Japan's Ministry of Finance bought about 9.8 trillion yen in late April and May 2024 and another 5.5 trillion in July 2024 after USDJPY passed 160, with single-day operations near 6 trillion yen moving the pair four to five yen in minutes. The Swiss National Bank intervenes routinely, and the People's Bank of China steers the yuan through its daily fix. Verbal intervention, rate checks and unscheduled statements precede actual buying. Intervention succeeds when aligned with fundamentals or coordinated, and only delays moves that are rate-driven; USDJPY rose above the intervention levels within weeks in 2022. Traders holding positions against an intervention-prone central bank must accept slippage that no stop loss will prevent."),
    ("The 2015 Swiss franc shock and broker failures", "On 15 January 2015 the Swiss National Bank abandoned its EURCHF floor of 1.20, held since 2011, without warning. The pair fell roughly 30% within minutes to below 0.90 before recovering near 1.03, and there was no continuous market in between: stops were filled hundreds of pips below their levels or not at all. Retail traders had treated the floor as riskless and ran leverage up to 200:1. Alpari UK went insolvent the next day, FXCM was left with 225 million dollars of negative client balances and survived only through a 300 million dollar loan, and IG lost about 30 million pounds. The episode showed that a stop loss is an instruction, not a guarantee, that pegged pairs carry hidden tail risk, and it led ESMA to mandate negative balance protection for retail accounts."),
    ("Retail broker models: market maker versus ECN", "A market maker or B-book broker takes the other side of client trades and profits when clients lose, which is a conflict of interest, though most losses are the client's own overtrading rather than manipulation. An STP or ECN broker passes orders to liquidity providers and charges a commission, typically 5 to 7 dollars per round-turn standard lot, on top of a raw spread of 0.1 to 0.3 pips on EURUSD. Spread-only accounts usually charge about 1 pip, equivalent to 10 dollars per lot, so raw plus commission is often cheaper. Many brokers run hybrids that A-book consistently profitable clients and B-book the rest. What matters is the all-in cost per trade, execution quality during news, and whether the broker's regulated entity, not its marketing brand, holds your money."),
    ("Leverage limits by regulator", "Regulators cap retail forex leverage because their own data showed that higher leverage raised the share of losing accounts. ESMA's 2018 product intervention, kept by EU national regulators and the UK FCA, sets 30:1 on major pairs, 20:1 on minors and gold, 10:1 on commodities, 5:1 on shares and 2:1 on crypto, plus a 50% margin close-out rule, negative balance protection, a ban on bonuses and a mandatory warning showing the percentage of clients losing money. The CFTC and NFA allow 50:1 on majors and 20:1 on others, require first-in-first-out closing and forbid holding both sides of a pair. ASIC adopted 30:1 in 2021 and Japan uses 25:1. Offshore licenses in places like Vanuatu or Seychelles permit 500:1 or more with none of the protections, which is the real trade-off when a broker advertises high leverage."),
    ("Regulation and broker selection", "Broker risk is counterparty risk. Tier-one regulators such as the FCA, ASIC, CFTC and NFA, BaFin, FINMA, MAS and Japan's FSA require segregated client money, capital adequacy and compensation schemes: the UK FSCS covers 85,000 pounds and the Cypriot investor fund 20,000 euros. Large brands operate several entities, and the offshore one that offers 500:1 leverage carries no protection, so check which legal entity appears on the account agreement and verify its license on the regulator's register. Warning signs are withdrawal complaints, bonus schemes that lock deposits, spreads that widen only against you, and unregulated introducing agents. Since the 2015 franc shock, negative balance protection and the broker's capital are the things standing between a gap and a debt."),
    ("How many retail forex traders lose", "US retail forex dealers must disclose quarterly under CFTC rule 5.5 the share of non-discretionary accounts that were profitable. In a typical quarter 60 to 75% of accounts lose money, with brokers ranging from roughly 55% to 70% unprofitable in mid-2026 disclosures. European brokers' mandatory ESMA warnings usually state that 70 to 85% of retail CFD accounts lose money. A French AMF study of nearly 15,000 clients over four years found 89% lost, with a mean loss of about 10,900 euros. Quarterly profitability is not persistent: winners in one quarter are often losers the next, and account lifetimes are short. The causes are spread and swap costs on high turnover, leverage that makes normal volatility fatal, and behavioral errors, not the market being rigged. The base rate should shape expectations and position sizing."),
    ("News trading around NFP, CPI and rate decisions", "US non-farm payrolls arrive on the first Friday at 08:30 Eastern, CPI mid-month at the same time, FOMC decisions at 14:00 Eastern with a press conference thirty minutes later, and the ECB at 14:15 CET followed by a press conference. EURUSD routinely moves 30 to 80 pips within minutes of a surprise, and the reaction depends on the gap between the print and the consensus, plus revisions and details like average hourly earnings. Strategies include pending-order straddles, fading the first spike, and waiting for the second move after the initial volatility. Straddles suffer because both orders can fill at terrible prices, and the first move often reverses. Systematic traders more often flatten or halve position size before releases, since news volatility is a cost to a trend or mean reversion model, not an edge."),
    ("Slippage and requotes during news", "In the seconds around a major release, liquidity providers pull quotes and spreads on EURUSD widen from under 1 pip to 5 to 20 pips; exotics go far wider. Market orders and triggered stop losses fill at the next available price, which can be tens of pips through the level, while limit orders may not fill at all. Dealing-desk brokers may requote, offering a new price instead of a fill, and ECN liquidity providers can reject orders under last look. Guaranteed stops exist at some brokers for a premium. Practical defenses are to keep stops outside the likely spread widening, size for a fill several spreads worse than expected, and audit the broker's execution statistics. A backtest that assumes fixed spreads and instant fills is most wrong exactly where news strategies claim their edge."),
    ("Asian range and London breakout setups", "The London breakout marks the high and low of the Asian session, roughly 00:00 to 07:00 UTC, and buys or sells a break of that range after the London open with a stop on the far side. The logic is that Asia is a consolidation and Europe brings the volatility expansion. Honest testing over long histories on EURUSD and GBPUSD shows raw win rates around 40 to 50% and only a small edge before costs, because many breaks are stop runs that reverse within the hour. It works better when the Asian range is narrow relative to the daily average true range, the break aligns with the higher timeframe trend and no major data is due; it fails on wide ranges and holidays. Treat it as a breakout trading template that needs filters and volatility-scaled stops, not a standalone system."),
    ("Trend following on currency futures versus spot", "Currency futures on CME (euro 6E, yen 6J, pound 6B, plus micro contracts) are exchange-cleared, transparent, and price the interest rate differential into the basis instead of charging swap; they also feed the Commitments of Traders report. Spot forex offers fractional sizing, 24-hour trading and lower minimums but adds swap costs and broker counterparty risk. Trend following on currencies as an asset class has produced a standalone Sharpe ratio near 0.3 to 0.5, lower than in commodities, with big years when rate cycles diverge such as 2014 and 2022 and long droughts in the low-volatility years from 2012 to 2020. Trends on a single pair are unreliable; the edge comes from a diversified basket with volatility targeting. Futures rolls and spot swaps both matter for multi-month holds."),
    ("Mean reversion and cointegration in currency pairs", "EURUSD and GBPUSD share the dollar leg, so their ratio is simply EURGBP, and a spread trade between them is a disguised EURGBP position with double the costs. Genuine cointegration tests such as Engle-Granger or Johansen sometimes pass for pairs like AUDUSD and NZDUSD or EURCHF and USDCHF over calm windows, with half-lives of days to weeks, but the relationships break at regime shifts: the 2016 Brexit vote knocked sterling 10% overnight and destroyed every sterling spread. Intraday mean reversion in majors exists but the retail spread consumes most of it. Triangular arbitrage keeps crosses consistent to within a pip, so there is no free convergence trade. Mean reversion in forex works best as a short-horizon overlay on range regimes with tight stop losses."),
    ("Currency correlations and hedging them", "Because pairs share currencies, their returns are mechanically correlated: EURUSD and USDCHF have historically run near minus 0.9, EURUSD and GBPUSD near plus 0.8, AUDUSD and NZDUSD near plus 0.85. A trader long EURUSD and short USDCHF holds nearly the same bet twice, so risk per trade must be computed on net currency exposure, not per ticket. Rolling correlations shift with regime, so use a recent window and expect changes around central bank divergence. Real hedging means offsetting exposure, for example long AUDJPY paired with long JPY against a risk currency, or using dollar index futures against a dollar-heavy book. Opening a long and a short in the same pair at one broker, often sold as hedging, pays two spreads and two swaps for zero exposure."),
    ("Volatility patterns: weekly cycle and holiday thinning", "Forex volatility follows a weekly rhythm: Monday mornings and Friday afternoons are quiet, Tuesday through Thursday carry most range, and payroll Fridays are exceptions. Sunday opens can gap after weekend news. Liquidity thins sharply between Christmas and New Year, on Japanese Golden Week and around bank holidays, and thin markets produce the worst flash crashes: sterling fell 6 to 9% in two minutes early on 7 October 2016 in Asian hours, and on 3 January 2019 USDJPY dropped from 109 to 105 in minutes during a Japanese holiday before recovering. Traders shrink position size, widen stops or stay out in thin windows, and normalize signals by time of day. Backtests that ignore these calendar effects overstate fills and understate slippage."),
    ("Position sizing in forex with pip risk", "Forex position size is derived from the stop distance: lots equal account risk divided by stop pips times pip value per lot. With a 10,000 dollar account risking 1% (100 dollars), a 25 pip stop loss on EURUSD at 10 dollars per pip per standard lot gives 0.4 lots. Add the spread to the stop distance, convert pip value for yen pairs and non-dollar accounts, and aggregate correlated positions as one exposure. Never size from the margin the broker allows, because 30:1 leverage on the whole account means a 3% adverse move wipes it out. Volatility-based stops using ATR keep risk consistent across pairs with different daily ranges. This arithmetic, done every time, is what separates surviving traders from the loss statistics."),
    ("Prop firm challenges and their economics", "Proprietary trading challenges sell an evaluation for a fee, typically 150 to 1,000 euros for a nominal 10,000 to 200,000 account, then require hitting a profit target, commonly 10% then 5% in two phases, without breaching a 5% daily or 10% total drawdown. Passing grants a simulated funded account with an 80 to 90% profit split; most firms do not place real trades, so the business model is fees from failed evaluations. Reported pass rates are near 10% per phase, and studies of several firms find roughly 5 to 7% of buyers ever receive a payout. Rules on news trading, consistency and weekend holding invalidate many strategies. The CFTC shut down My Forex Funds in 2023. Treat the fee as the premium on a leveraged option and size for the drawdown rule, not the target."),
    ("Copy trading and signal services", "Copy trading platforms such as eToro, ZuluTrade and the MQL5 signals market let followers mirror a leader's trades; Telegram groups sell signals outright. Assess a track record on length (years, not months), maximum drawdown, and whether the strategy uses grid or martingale averaging, which shows smooth equity until a single blow-up. Followers suffer slippage between the leader's fill and their own, and pay the platform through wider spreads. Many signal sellers are paid introducing-broker rebates on the volume their followers trade, so their incentive is turnover rather than profit, and posted results are often demo accounts or cherry-picked screenshots. Survivorship bias is total: leaders who failed are deleted. A verified third-party track record with real money over several years is the minimum before risking capital."),
    ("MetaTrader and Expert Advisors", "MetaTrader 4 and 5 are the dominant retail forex platforms, and Expert Advisors are automated strategies written in MQL4 or MQL5 that run inside them. The built-in strategy tester models ticks from one-minute bars unless supplied with real tick data, defaults to a fixed spread and ignores swap and slippage unless configured, which is why marketplace EAs show beautiful curves that die live. Most sold EAs are grid, martingale or tight-stop scalpers, all of which trade small steady gains for a rare catastrophic loss. Broker server time and GMT offset affect any time-based logic, and a virtual private server near the broker keeps latency low. With tick data, variable spreads and walk-forward tests it is a workable research tool; as a store of black boxes it is a way to lose money automatically."),
    ("Backtesting forex with tick data and variable spreads", "Forex has no consolidated tape, so historical data comes from individual providers such as Dukascopy, TrueFX, HistData or the broker itself, and results differ between them. Spreads vary by hour, from 0.1 pips in the London-New York overlap to several pips in the early Asian session and far more during news, so a backtest with fixed spreads flatters intraday and scalping strategies most. Include commission, swap on every rollover with triple charges on Wednesday, Sunday gaps and slippage as a multiple of spread. Align timestamps to a single timezone and decide the daily bar boundary, since a New York 17:00 close produces five candles per week while a UTC close produces a Sunday sliver. Run walk-forward tests and check the strategy on data from a second provider before trusting it."),
    ("Yield spreads and the fixed-income link", "Currency pairs are often best explained by bond yield spreads. USDJPY has tracked the gap between US and Japanese ten-year yields with correlations above 0.8 during 2021 to 2024, and two-year spreads capture policy expectations for most majors. Real yields, nominal yields minus expected inflation, matter for the dollar against gold-like currencies such as the franc. Traders watch overnight index swaps to see how many hikes or cuts are priced and trade the pair when the spread moves before the currency does. The link weakens when both central banks sit at the zero bound, when risk-off flows dominate as in March 2020, or when intervention caps a rate-driven move. Treat the spread as the fundamental anchor and use price action for timing."),
    ("FX options and risk reversals as sentiment", "Currency options are quoted in implied volatility rather than price, with the market organized around 25-delta calls and puts. A risk reversal is the implied volatility of the 25-delta call minus the 25-delta put; a negative EURUSD risk reversal means traders pay more for euro downside protection. The butterfly measures demand for tails. Traders use risk reversals as a positioning gauge, fading extremes, and compare implied with realized volatility around events to decide whether to buy or sell options. Large option expiries at the 10:00 New York cut can pin spot near strikes. Data is available from CME currency options and some brokers; retail access to over-the-counter FX options is limited. The indicator fails when the skew reflects hedging flows rather than directional views, so read it alongside the Commitments of Traders report."),
    ("Commitments of Traders for currencies", "The CFTC publishes the Commitments of Traders report each Friday at 15:30 Eastern, showing positions in currency futures as of the prior Tuesday. The legacy format splits commercials from non-commercials, while the Traders in Financial Futures format separates dealers, asset managers and leveraged funds. Traders track net speculative positioning as a percentage of open interest or its multi-year percentile and treat extremes as contrarian: leveraged funds held a record net yen short of roughly 180,000 contracts in mid-2024 shortly before the August unwind. The limits are real: futures are a few percent of forex turnover, the data is three days old, and positioning can stay extreme for months in a trend. Use it to size and to avoid crowded trades, not to time entries."),
    ("Interbank market structure, dealers and last look", "The BIS survey for April 2025 measured 9.5 trillion dollars of daily forex turnover, with FX swaps at 4 trillion, spot at 3 trillion and forwards near 1 trillion. The core is a tiered dealer market: a handful of banks quote on the primary venues, EBS for the euro and yen and LSEG Matching for sterling and the Australian dollar, and on their own single-dealer platforms, while hedge funds and retail brokers access this through prime brokers and ECN aggregators. Under last look a liquidity provider can reject a trade after a brief hold if the price moved, which the FX Global Code constrains but permits. Retail quotes are aggregated one tier down, so broker volume indicators show that broker's flow only. There is no central exchange or consolidated tape, and prices differ slightly between venues."),
    ("The 4pm London fix and month-end flows", "The WM/Reuters benchmark fix at 16:00 London time, computed over a five-minute window, is the rate used to value funds and settle many corporate hedges, so large real-money orders are executed against it. Month-end and quarter-end fixes concentrate portfolio rebalancing flows, and pairs regularly move 30 to 60 pips into the fix and partially reverse afterwards. Banks were fined about 10 billion dollars in 2014 and 2015 for coordinating trades ahead of the fix using client order information, which led to the wider window and the FX Global Code. Traders use the fix as a liquidity event: avoid stops near it, expect spread widening and mean reversion after it, and model month-end demand using equity and bond market performance, since a strong US stock month implies foreign investors sell dollars to rebalance."),
    ("Crypto and forex market differences", "Crypto trades 24/7 on centralized and decentralized exchanges where the venue is also the custodian, while forex trades 24/5 through brokers and dealers with no consolidated market. Volatility is an order of magnitude apart: bitcoin runs 50 to 80% annualized against 6 to 10% for EURUSD, so strategies need volatility scaling before they port. Perpetual futures funding rates play the role that swap plays in forex, and stablecoins act as dollar proxies. Crypto spreads and slippage are wider, exchange failures like FTX replace broker failures like Alpari, and regulation is thinner. Momentum and trend following have been stronger in crypto because retail dominates flow, while carry is weaker because there is no interest rate differential to anchor it. Risk-on correlation means crypto often trades like a leveraged AUDJPY."),
    ("Common retail mistakes in forex", "The recurring errors are using the broker's maximum leverage, trading without a stop loss or moving it, averaging into losers with grid or martingale logic, and scalping pairs whose spread is a large fraction of the target, since a 1 pip spread on a 10 pip scalp is a 10% cost per trade. Traders ignore swap on multi-week holds, miscalculate pip value on yen pairs, trade the news with market orders into widened spreads, and hold positions through rollover on exotics. Many buy marketplace Expert Advisors or follow signal channels with no verified history, and deposit with an offshore entity of a regulated brand. Behavioral errors such as revenge trading and oversizing after wins finish the job. Each of these shows up directly in the 70 to 85% loss rates regulators publish."),
    ("Forward rates, covered interest parity and the cross-currency basis", "A forward exchange rate equals spot adjusted for the interest rate differential over the term: forward equals spot times one plus the quote-currency rate divided by one plus the base-currency rate. Covered interest parity holds because any deviation is a riskless arbitrage for banks, so forward points are quoted in interest rate terms and the higher-yielding currency trades at a forward discount. Since 2008 a persistent cross-currency basis has opened, especially in dollar-yen and dollar-euro, reflecting bank balance sheet costs and dollar funding demand, and it widens sharply at year-end and in crises. For traders the practical uses are pricing swap charges, hedging foreign assets, and reading a widening basis as a signal of dollar funding stress that usually coincides with the crisis side of the dollar smile."),
]

SOURCES = {
    "feeds": [
        "https://www.fxstreet.com/rss/news",
        "https://www.forexlive.com/feed/",
        "https://www.babypips.com/feed.rss",
        "https://www.actionforex.com/feed/",
        "https://www.marketpulse.com/feed/",
        "https://www.federalreserve.gov/feeds/press_all.xml",
        "https://www.ecb.europa.eu/rss/press.html",
    ],
    "subreddits": ["Forex", "Daytrading", "algotrading", "Trading", "FuturesTrading"],
    "github_queries": [
        "topic:forex",
        "topic:forex-trading language:python",
        "topic:metatrader5 python",
        "topic:currency-trading backtest",
        "dukascopy tick data downloader",
    ],
    "arxiv_topics": [
        "foreign exchange carry trade returns",
        "exchange rate forecasting interest rate differential",
        "FX market microstructure last look",
        "currency momentum and mean reversion",
        "cross-currency basis covered interest parity",
    ],
    "urls": [
        "https://www.bis.org/statistics/rpfx25_fx.htm",
        "https://www.bis.org/press/p250930.htm",
        "https://www.babypips.com/learn/forex",
        "https://www.cftc.gov/MarketReports/CommitmentsofTraders/index.htm",
        "https://www.nfa.futures.org/members/member-resources/files/forex-regulatory-guide.html",
        "https://www.ecfr.gov/current/title-17/chapter-I/part-5/section-5.5",
        "https://www.esma.europa.eu/press-news/esma-news/esma-agrees-prohibit-binary-options-and-restrict-cfds-protect-retail-investors",
        "https://www.federalreserve.gov/releases/h10/",
    ],
}
