"""Knowledge pack: market microstructure, execution and trading infrastructure.

How orders become prices, what it costs to trade, and how a live system is
wired so that it keeps trading correctly. Deeper companions to the curriculum
cells on market microstructure, market making, transaction costs and crypto
market structure, under different titles so nothing is duplicated.
"""

from __future__ import annotations

DOMAIN = "Market microstructure, execution and trading infrastructure"

LESSONS: list[tuple[str, str]] = [
    ("Limit order book and price-time priority", "A limit order book is two sorted queues of resting orders: bids from highest price down, asks from lowest price up. The best bid and best ask form the top of book; their difference is the bid-ask spread and their midpoint is the reference price. Most electronic venues match by price-time priority: the best price fills first, and among equal prices the earliest order fills first. An incoming marketable order walks through levels until filled, which is how market impact arises. Some futures contracts allocate pro-rata, rewarding size instead of speed. Depth per level is visible in level 2 market data, but hidden and iceberg orders mean displayed depth understates true liquidity, and displayed depth is often cancelled before it can be hit."),
    ("Order types in depth", "A market order demands immediate execution at whatever prices are available; a limit order rests at a price and may never fill. A stop order becomes a market order when a trigger price trades; a stop-limit becomes a limit order, which avoids gap fills but risks not filling at all. Immediate-or-cancel (IOC) fills what it can and cancels the rest; fill-or-kill (FOK) needs the whole quantity at once. Post-only orders are rejected if they would cross the spread, guaranteeing maker status. Iceberg orders display a slice and hide the remainder, losing time priority on each refresh. Pegged orders float with the midpoint or the best quote. Choosing the type is choosing between price certainty, fill certainty and information leakage."),
    ("Maker-taker fees and rebates", "Most exchanges charge takers, who remove liquidity with marketable orders, and pay makers, whose resting limit orders get hit. In US equities the cap is 30 mils, 0.30 cents per share; typical schedules charge takers about 0.30 cents and rebate makers about 0.20. Crypto exchanges quote basis points, often 2-5 for makers and 4-10 for takers, with volume tiers. Inverted venues pay takers and charge makers to attract aggressive flow. Fees change routing: a broker chasing rebates may route to venues with long queues where fills are slower and more adversely selected. For a strategy, the gap between paying and earning the fee can be the entire edge, so backtests must model the fee schedule the account actually gets."),
    ("Components of the bid-ask spread", "The quoted spread compensates liquidity providers for three costs. Order processing cost covers technology, clearing and capital, and is small in liquid markets. Inventory cost is the risk of holding a position the market maker did not want; it rises with volatility and falls with the ability to hedge. Adverse selection cost is the loss to informed traders: whoever hits a quote knows something on average, so the price moves against the maker after the trade. Empirically adverse selection dominates in equities; the realized spread, measured against the midpoint a few seconds later, is far smaller than the quoted spread. Spreads widen around news, at the open and when volatility rises, because inventory and adverse selection costs both rise."),
    ("Order flow imbalance as a predictor", "Order flow imbalance measures net buying pressure from order book changes: increases in bid size or decreases in ask size count as buying, and vice versa. Cont, Kukanov and Stoikov showed that over short horizons the next price change is roughly linear in this imbalance, with a slope inversely proportional to depth. Simpler versions use signed trade volume, classified by whether trades hit the bid or the ask. The predictive power is real but decays within seconds to minutes and is mostly consumed by the spread and fees, so it is an execution and market making signal rather than a directional strategy for slow traders. Aggregated over days, imbalance still explains much of daily returns, which is why institutional flow is watched so closely."),
    ("Square-root law of market impact", "Across equities, futures, options and crypto, the price impact of a metaorder of size Q is roughly volatility times the square root of Q divided by daily volume, with a prefactor near one. Doubling the order raises impact by about 41%, not 100%, so impact per share falls with size while total cost rises. Impact is partly temporary and decays after the order finishes, leaving a permanent component of roughly half to two thirds of the peak. The law holds from about 0.1% to 10% of daily volume. Traders use it to estimate capacity: a strategy with 20 basis points of gross edge per trade cannot trade beyond the size at which impact eats that edge. Linear impact models overstate cost for large orders and understate it for small ones."),
    ("Almgren-Chriss optimal execution", "Almgren and Chriss framed execution as a trade-off between market impact, which favours trading slowly, and price risk, which favours finishing quickly. With linear temporary and permanent impact and a mean-variance objective, the optimal schedule trades a fixed fraction of the remaining quantity per period, an exponentially decaying trajectory whose speed depends on risk aversion, volatility and the impact coefficients. Zero risk aversion recovers a straight-line TWAP. The efficient frontier of expected cost against variance lets a desk choose an urgency. The model assumes known constant parameters and no reaction from other participants, which is false: impact is closer to square-root and other traders detect predictable schedules. It remains the reference for building and calibrating execution algorithms."),
    ("TWAP, VWAP, POV and implementation shortfall algorithms", "Execution algorithms slice a parent order into child orders. TWAP spreads them evenly over time, simple but predictable. VWAP follows the historical intraday volume curve, trading more at the open and close, and is judged against the day's volume-weighted average price. Percentage of volume (POV) trades a fixed share of realized volume, typically 5-20%, so it speeds up when the market is active and never finishes if volume dries up. Implementation shortfall, or arrival price, algorithms front-load trading to cut the risk of the price drifting from the decision price, following Almgren-Chriss logic. Each algorithm is a benchmark choice: a VWAP algo that beats VWAP may still have paid more than the arrival price. The signal decay of the strategy decides which benchmark matters."),
    ("Slippage measurement and transaction cost analysis", "Implementation shortfall, defined by Perold, is the difference between the paper return at the decision price and the actual return after all costs. It decomposes into delay cost from decision to first order, execution cost from arrival price to average fill, opportunity cost on the unfilled part, and explicit fees. Transaction cost analysis (TCA) measures these in basis points against benchmarks such as arrival midpoint, VWAP and the close. Typical institutional shortfall in liquid US large caps is 10-30 basis points; small caps and crypto altcoins run to 100 or more. Track slippage per strategy and per venue over time, because rising slippage is the first sign that a strategy is crowded or the market has changed. Backtests should use measured live slippage, not an assumed constant."),
    ("Dark pools and hidden liquidity", "Dark pools are venues that display no quotes; orders match, usually at the midpoint of the lit market, and print to the tape only after execution. In the US around 40% of equity volume trades off-exchange, split between dark pools, wholesalers and block venues. The attraction is less information leakage and midpoint prices for large orders; the cost is uncertain fills and the risk of trading against faster participants who ping the pool to detect size. Lit exchanges also carry hidden orders and iceberg remainders. Dark liquidity is why displayed depth is a poor measure of what can be traded, and why routers sweep dark venues before crossing the lit spread. Europe caps dark trading; the US does not."),
    ("Payment for order flow and retail execution quality", "US retail brokers route most marketable orders to wholesalers such as Citadel Securities and Virtu, who pay the broker for the flow and fill it internally, usually with a small price improvement inside the national best bid and offer. Wholesalers profit because retail orders are uninformed on average, so adverse selection is low. Payment is well under a cent per share but is a major revenue line for zero-commission brokers. Execution quality is reported under SEC Rules 605 and 606: effective spread, price improvement and fill speed. Critics argue that competition for retail flow happens off-exchange, thinning lit quotes. For a small algorithmic trader, marketable orders often fill at or better than the displayed quote, but resting limit orders may fill less often behind internalisation."),
    ("Opening and closing auctions", "Equity exchanges open and close with call auctions: orders accumulate and a single clearing price is set that maximizes matched volume, with imbalance information published in the minutes before. The closing auction is the largest liquidity event of the day, often 10% or more of daily volume in US large caps, because index funds and benchmarks reference the close. Auction prices are less noisy than continuous trading and let large orders trade with little spread cost, which is why many systematic strategies execute market-on-close. The risks are a gamed imbalance and a price set by a few large orders; expiration days and index rebalances produce extreme closing volumes. Backtests that fill at the close should check that the strategy's size is small relative to auction volume."),
    ("Latency arbitrage and colocation", "Latency arbitrage exploits the time it takes for a price change on one venue to reach another: a fast trader who sees the futures tick in Chicago can hit stale quotes in New Jersey before they update. The relevant times are microseconds; the Chicago to New Jersey round trip is about 8 milliseconds by microwave and 13 by fibre. Colocation puts servers in the exchange data centre so that market data and order entry travel metres rather than kilometres. Aquilina, Budish and O'Neill estimated latency arbitrage races cost about 0.5 basis points of volume in UK equities. For anyone not at the speed frontier the lesson is defensive: never rest orders that a faster participant can pick off after a related market moves."),
    ("Tick size and its effects", "The tick size is the minimum price increment. When the tick is large relative to the price, spreads are pinned at one tick, queues are long and time priority is valuable, so speed matters and displayed depth is large. When the tick is small, spreads are narrow, queues are short, and depth is thin and flickers. US equities moved from sixteenths to pennies in 2001, cutting spreads and depth together; the 2016-2018 Tick Size Pilot widened ticks for small caps and found little benefit. Futures ticks vary by contract, and crypto exchanges often allow ticks far below the natural spread. The tick decides the strategy: in a tick-constrained market, queue position modelling is the edge; in a fine-tick market, price improvement by a fraction of a tick is."),
    ("Queue position modelling", "Where the spread is one tick, a resting limit order fills only when everything ahead of it in the queue has traded or cancelled. The value of an order therefore depends on its position: at the front of a large queue it is a free option that fills before the price moves against it, while at the back it fills mostly when the level is about to be swept, which is adverse selection. Traders estimate queue position from their own order timestamp and the level 2 or level 3 feed, and fill probability from the rate of trades and cancellations ahead. Cancelling and replacing sends an order to the back. This is why backtests that fill a limit order whenever price touches it are badly optimistic: touch is not fill."),
    ("Spoofing and layering", "Spoofing is placing orders with the intent to cancel them before execution, to create a false impression of supply or demand, typically to move the price so that a genuine order on the other side fills better. Layering stacks several such orders at successive levels. Both are illegal in the US under the Dodd-Frank Act and are prosecuted by the CFTC, SEC and Department of Justice; Navinder Sarao was charged for spoofing E-mini futures around the 2010 flash crash, and banks have paid fines of hundreds of millions for precious metals spoofing. Detection uses order-to-trade ratios and cancellations after opposite-side fills. Any logic that places orders it does not intend to fill, even to probe liquidity, needs legal review, and high cancel rates invite exchange scrutiny."),
    ("The 2010 flash crash", "On 6 May 2010 the S&P 500 dropped about 9% in minutes and recovered within half an hour. A large sell program in E-mini futures, executed as a percentage of volume without regard to price, met thin liquidity; high frequency market makers absorbed inventory, passed it back and forth in a hot potato pattern, then withdrew. Cross-market arbitrage spread the fall to ETFs and single stocks, some of which printed at a cent or at 100,000 dollars against stub quotes. Around 20,000 trades were cancelled. Lessons: liquidity is not constant, POV algorithms feed on their own impact in a vacuum, stub quotes and market orders are dangerous together, and every trading system needs price sanity checks. The event led to single-stock circuit breakers and later limit up-limit down."),
    ("Circuit breakers and limit up-limit down", "Market-wide circuit breakers in US equities halt trading for 15 minutes when the S&P 500 falls 7% or 13% from the prior close before 3:25 pm, and for the day at 20%; they fired four times in March 2020. Limit up-limit down (LULD) sets per-stock bands, usually 5% or 10% around a rolling five-minute reference price, doubled in the first and last minutes of the day; a stock stuck at a band for 15 seconds is paused for five minutes. Futures exchanges use daily price limits and brief dynamic halts when a contract moves too far in a few seconds. Crypto exchanges mostly have no halts, so liquidation cascades run unchecked. Trading systems must handle halted symbols: orders queue, rejections spike, and stops cannot execute during a pause."),
    ("Short selling mechanics, borrow costs and squeezes", "To sell a stock short, the broker locates shares to borrow, the short sells them, and the position closes by buying back and returning them. The lender is paid a borrow fee: near the risk-free rate for easy-to-borrow names, and from 10% to several hundred percent annualized for hard-to-borrow ones. The short also owes dividends. Loans are recallable, so a short can be forced to cover at the worst time. A squeeze happens when rising prices force covering that lifts prices further; GameStop in January 2021 had short interest above 100% of float and borrow rates above 80%. Regulation SHO requires locates and closes out failures to deliver. Backtests of short strategies must include borrow cost and availability, which remove most of the paper profit in small caps."),
    ("Settlement, clearing and T+1", "A trade is executed on the exchange, cleared by a central counterparty that becomes buyer to every seller and seller to every buyer, netting obligations and collecting margin, and finally settled when cash and securities move. US equities moved from T+2 to T+1 settlement in May 2024; India moved earlier. Futures are marked to market daily through the clearing house with initial and variation margin. Crypto spot on a centralized exchange settles instantly in the exchange's ledger, but only against the exchange's credit. Settlement matters because cash from a sale is not available until it settles, free-riding rules limit rebuying with unsettled funds in cash accounts, and clearing margin is what forces liquidations in stress. Reconciliation must compare positions at trade date and settlement date."),
    ("Crypto matching and liquidation engines", "A crypto exchange runs a matching engine per market, usually price-time priority with a single-threaded sequencer for determinism, and a separate risk engine that watches every leveraged account. When margin falls below the maintenance level, the liquidation engine takes the position and sells it into the book, in slices or at once; losses beyond the bankruptcy price hit the insurance fund, and if that is exhausted, auto-deleveraging closes profitable positions on the other side. Liquidations appear as clustered market orders and cause cascades in which one forced sale triggers the next, which is why traders watch liquidation levels and open interest. Matching engine outages during volatility are common; a system must handle stale order books, rejected cancels and positions it cannot close."),
    ("Perpetual futures funding rate mechanics", "A perpetual swap has no expiry, so a funding payment keeps its price near spot. Every eight hours on most exchanges, if the perp trades above its index, longs pay shorts a rate proportional to the premium plus a small interest component, usually 0.01% per period; if below, shorts pay longs. Because payment flows between traders in proportion to position size, a delta-neutral position long spot and short perp earns the funding, the cash and carry or basis trade, which in bull markets has paid 20-50% annualized and turns negative in bear markets. Funding is a crowding gauge: extreme positive funding marks leveraged longs that liquidation cascades unwind. Backtests must apply funding at exact timestamps using the exchange's own index."),
    ("DEX automated market makers, impermanent loss and MEV", "A constant product automated market maker such as Uniswap holds reserves x and y and prices every trade so that x times y stays constant, so large trades get worse prices: a deterministic, explicit market impact. Liquidity providers earn fees but suffer impermanent loss, because the pool sells the rising asset; a 2x move in one asset costs about 5.7% versus holding, and a 5x move about 25%. Concentrated liquidity amplifies both fees and this loss. Every transaction is public before inclusion, so searchers extract maximal extractable value by front-running, back-running and sandwiching swaps, paying validators for ordering. Traders set slippage tolerance tightly, use private transaction relays, and treat quoted DEX prices as pre-MEV. On-chain execution is atomic, removing settlement risk but not ordering risk."),
    ("Futures roll mechanics and calendar spreads", "A futures contract expires, so a continuous position must be rolled: close the front month and open the next, usually in a roll window a week or two before expiry when liquidity has migrated. The price difference between the contracts is the calendar spread, driven by carry, storage, dividends or funding. Rolling in contango is not itself a cost, but the continuous series drifts down as each contract converges to spot. Exchanges list calendar spreads as single instruments with one tick and one fill, the cheapest way to roll. Backtesting needs a stitched continuous contract: back-adjusting by the roll gap preserves point returns but can produce negative historical prices, while ratio adjustment preserves percentage returns. Volume-based roll dates avoid trading an illiquid front month."),
    ("FX market structure, ECNs and last look", "Spot FX is an over-the-counter dealer market turning over roughly 7 trillion dollars a day. Banks and non-bank market makers quote clients directly and on electronic communication networks and primary venues such as EBS and Refinitiv Matching, where the interbank price is discovered. Retail and small institutions trade through brokers who either pass orders to liquidity providers or internalise them. Last look lets a liquidity provider reject a trade after seeing it, nominally to check credit and stale prices; in practice it shifts adverse selection back to the taker, and reject rates rise in fast markets. The FX Global Code governs disclosure. EUR/USD spreads are a fraction of a pip for institutions, wider for retail, and liquidity thins sharply around the 5 pm New York rollover."),
    ("Options market making and the greeks of a book", "An options market maker quotes hundreds of strikes and expiries and manages the aggregate book: net delta is hedged in the underlying continuously, gamma decides how often and how expensively that hedging happens, vega is exposure to implied volatility moves across the surface, and theta is the daily decay the book earns or pays. Quotes come from a fitted volatility surface plus a spread that widens with gamma risk. Being short gamma near expiry is the classic way to lose a year of edge in an afternoon. Pin risk, early exercise before dividends, and hedging with stock versus futures all matter. Retail flow skews to buying short-dated calls, so the dealers' aggregate position drives intraday behaviour around strikes with large open interest."),
    ("Market data: L1, L2, L3 and the consolidated tape", "Level 1 data is the best bid and offer with sizes plus the last trade. Level 2 adds aggregated depth at each price level, usually five to twenty levels. Level 3, or order-by-order data, shows every add, modify, cancel and execution with order identifiers, which queue position and order flow imbalance models need. In US equities the consolidated tape (SIP) aggregates every exchange's top of book and trades but arrives later than direct feeds, by hundreds of microseconds to a millisecond, which matters only to the fastest participants. Crypto exchanges offer level 2 snapshots plus incremental diffs over websocket; reconstruction means applying diffs in sequence with gap detection. Historical level 3 data is expensive and huge, so most research uses level 2 sampled at events or fixed intervals."),
    ("Backtesting with bid-ask data versus mid prices", "A backtest that fills at the mid price or the close assumes away the spread, which for a strategy trading many times a day is usually the whole result. The minimum honest model fills buys at the ask and sells at the bid at decision time, plus fees and an impact term that grows with size. For limit orders it is harsher: assume a fill only when price trades through the limit, not when it touches, or model queue position explicitly. The signal timestamp must precede the fill timestamp by the system's real latency. Run the backtest with fills at bid and ask, at mid, and at the worst price in the bar; if the ranking of strategies changes, the edge lives in the execution assumption, not the signal."),
    ("Live trading infrastructure and the event loop", "A live system is an event loop that consumes market data and fills, updates state, decides, and sends orders without blocking. The pieces are a market data handler that maintains the order book, a strategy that turns state into target positions, a portfolio and risk layer that converts targets into orders within limits, an order management system (OMS) that tracks each order through new, acknowledged, partially filled, filled, cancelled and rejected states, and an execution gateway per venue. The hardest bugs are asynchronous: a cancel arriving after a fill, a fill for an order the system forgot, a reconnect replaying old messages. Keep strategy logic and network input on separate threads or processes with queues between them, so a slow strategy cannot stall market data."),
    ("Reconciliation of positions and orders", "The system's belief about its positions, open orders and cash drifts from the broker's truth through missed fills, rejected messages, partial fills during a disconnect, manual trades, fees and corporate actions. Reconciliation compares the two at fixed intervals, at every reconnect and at start of day, and decides what wins: usually the broker's report for positions and the system's intent for targets. A discrepancy must halt new trading in that symbol until resolved, because a system that thinks it is flat when it is long doubles its exposure. Persist state on every change so a crash and restart can rebuild from the log plus a fresh broker snapshot. Reconcile realised profit and loss against statements too; a fee or funding line the system does not model is a slow leak."),
    ("API rate limits and websocket handling", "Every broker and exchange API limits request rates, for example a number of order messages per second and a weight budget per minute for REST calls, and returns errors or temporary bans when exceeded. A live system tracks its own budget, prefers websocket streams for data and order updates, and uses REST only for snapshots and recovery. Websocket connections drop routinely: the client must send heartbeats, detect silence, reconnect with exponential backoff, resubscribe, and re-synchronise the order book from a snapshot because messages were missed. Sequence numbers on incremental updates detect gaps. An order update over the socket can precede the REST acknowledgement of the same order, so the OMS must accept updates for orders sent but not yet confirmed."),
    ("Broker choice for algorithmic trading", "Interactive Brokers offers the widest reach for retail-sized algorithms: stocks, options, futures and FX across many countries, low commissions and margin rates, and an API through Trader Workstation or Gateway that is powerful but stateful and quirky, with pacing limits and market data fees. Alpaca provides a clean REST and websocket API for US equities and some crypto, commission-free with payment for order flow and easy paper trading, at the cost of narrower coverage. Crypto exchanges expose their own REST and websocket APIs, with the best liquidity on the largest venues and counterparty risk on all of them. Beyond fees, judge API reliability, fill quality, the ability to short, historical data access, and whether the paper environment matches production."),
    ("Paper trading versus live trading", "Paper trading tests the plumbing, not the edge. Simulated fills are optimistic: paper systems fill limit orders on touch and market orders at the displayed quote, with no queue, no partial fills and no impact, so paper profit overstates live profit, sometimes by the entire margin. Latency and rejects are absent too. What paper trading does verify is the order lifecycle, reconnection, reconciliation, and that the strategy behaves as the backtest did on the same data, a separate and important test called shadow trading. The path is backtest, then paper for weeks, then live at the smallest size the venue allows, comparing live fills with paper and backtest assumptions and fixing the cost model before scaling. Traders also override live systems in drawdowns they would have ignored on paper."),
    ("Pre-trade risk checks and kill switches", "Every order should pass checks before leaving the system: price within a band around the last trade or quote, size below a per-order maximum, resulting position within per-symbol and portfolio limits, notional and daily loss under thresholds, order rate below a limit, and the symbol not halted or restricted. These are cheap and prevent the class of errors that end firms; Knight Capital lost 440 million dollars in 45 minutes in 2012 when stale code sent orders with no such checks. A kill switch cancels all open orders and stops new ones, triggered by a human, a loss limit, a reconciliation failure or loss of market data, and must be testable in production. Enable the broker's own kill switch and cancel-on-disconnect too."),
    ("Monitoring and alerting for a running system", "A running system must prove it is alive and sane: heartbeat metrics per connection, message rates and latencies, order acknowledgement times, reject counts, fill rates, and position and profit and loss against expectation. Alert on absence as much as presence, because a silent feed looks like a calm market. Compare realised slippage per fill with the cost model in real time, and compare the live strategy's signals with a parallel backtest on the same data to catch drift and bugs. Dashboards are for humans; alerts go to a phone and escalate. Log everything with timestamps and sequence numbers so a post-mortem can replay the day. Rate-limit the alerts themselves, since an alert storm during a market event is when the operator most needs clarity."),
    ("Timestamps, clock synchronisation and data alignment", "A trade record has several times: when the exchange matched it, when the feed published it, when the system received it, and when the system acted. Serious systems use NTP or PTP and log both exchange and receive timestamps. Data from different venues and vendors carry different clocks and time zones, and daylight saving shifts silently misalign a year of joined data. Bars are ambiguous: a bar labelled 10:00 may cover the minute ending or beginning then, and futures daily bars follow different session definitions. Joining a signal from one source to prices from another by nearest timestamp introduces look-ahead if the signal's bar closes later than the price used. Store everything in UTC at microsecond precision or better and keep raw feed timestamps."),
    ("Corporate actions and data adjustment", "Stock splits, dividends, spin-offs, rights issues, mergers and ticker changes all break a raw price series. A 4-for-1 split shows as a 75% crash unless prices are adjusted; a large special dividend looks like a drop. Adjusted prices scale history backward so returns are correct, but they change every time a new action occurs, so a value stored last year differs from today's adjusted value for the same date, and adjusted prices can be tiny decades back. Use unadjusted prices for anything involving actual order sizes, tick sizes and price levels, and adjusted prices for returns. The ex-date, not the pay date, is when the price drops for a dividend. Symbol changes and delistings need point-in-time mappings to avoid survivorship bias. Crypto has analogues: token migrations, redenominations and exchange delistings."),
    ("Hidden costs of order cancellation and message rates", "Cancelling and replacing orders is not free even when the exchange charges nothing. Each replace sends the order to the back of the queue, and exchanges monitor order-to-trade ratios, with fees or warnings for participants who cancel far more than they trade. High cancel rates also leak information: quotes that vanish whenever the market moves mark a participant as a latency-sensitive maker and attract sniping. For a strategy that requotes on every tick, the useful measures are fill rate per order and adverse selection per fill. A slower requoting schedule with wider quotes often earns more net than an aggressive one, because it keeps queue position and stays within the message budget. Broker APIs reject bursts, so the OMS needs a queue that prioritises cancels over new orders."),
    ("Venue fragmentation and smart order routing", "US equities trade on sixteen exchanges plus dozens of dark venues, and Regulation NMS forbids trading through a better displayed price on another exchange. A smart order router splits a marketable order across venues by displayed depth, fees, expected hidden liquidity and latency, and sweeps them near simultaneously so quotes are not removed by others in between. For resting orders the router picks the venue with the shortest queue or largest rebate, a real trade-off since high-rebate venues have longer queues. Crypto is fragmented across exchanges with no routing rule, so the same coin trades at different prices for seconds, the cross-exchange arbitrage that funds market makers there. A small trader mostly inherits the broker's routing; understanding it explains why fills differ from the displayed quote."),
    ("Adverse selection and the winner's curse in execution", "Whenever a passive order fills, it fills because someone chose to trade against it, and that someone is on average better informed at that instant. This is adverse selection, and it shows up as the price moving against the filled order immediately afterwards. Measured as markout, the difference between the fill price and the midpoint seconds or minutes later, it is the main reason limit order strategies that look profitable in backtests lose money live. It is strongest just before scheduled news, when a related market has just moved, at the back of a long queue, and in the last moments before a level is swept. Execution algorithms counter it by pulling quotes when related markets move, not resting through announcements, and comparing markouts across venues."),
]

SOURCES = {
    "feeds": [
        "https://www.sec.gov/news/pressreleases.rss",
        "https://www.cftc.gov/RSS/RSSGP/rssgp.xml/all",
        "https://www.marketsmedia.com/feed/",
        "https://blog.quantinsti.com/rss/",
        "https://blog.janestreet.com/feed.xml",
        "https://mechanicalmarkets.wordpress.com/feed/",
        "https://blog.headlandstech.com/feed/",
    ],
    "subreddits": ["algotrading", "quant", "quantfinance", "interactivebrokers", "Daytrading"],
    "github_queries": ["topic:order-book", "topic:market-making", "topic:hft", "topic:limit-order-book", "topic:mev"],
    "arxiv_topics": ["limit order book", "optimal execution", "market impact", "order flow imbalance", "high frequency trading"],
    "urls": [
        "https://www.sec.gov/marketstructure",
        "https://www.sec.gov/rules/final/34-51808.pdf",
        "https://www.finra.org/rules-guidance/key-topics/best-execution",
        "https://www.luldplan.com/",
        "https://www.nasdaqtrader.com/Trader.aspx?id=NewsRSS",
        "https://www.cmegroup.com/rulebook/CME/",
        "https://www.dtcc.com/ust1",
        "https://interactivebrokers.github.io/tws-api/",
        "https://docs.alpaca.markets/",
        "https://ethereum.org/en/developers/docs/mev/",
    ],
}
