"""Knowledge pack: options and volatility trading, in depth.

Goes deeper than the curriculum's "Options and the Greeks", "Volatility",
"Hedging" and "Tail risk and fat tails" cells without repeating their titles.
Every lesson is one dense paragraph: mechanics, typical numbers, how it is
traded, the risks, and what the evidence says.
"""

from __future__ import annotations

DOMAIN = "Options and volatility trading"

LESSONS: list[tuple[str, str]] = [
    ("Black-Scholes assumptions and where they break", "Black-Scholes prices a European option assuming the underlying follows geometric Brownian motion with constant volatility, continuous frictionless hedging, a constant risk-free rate and no jumps or dividends. The price is a delta-hedging argument: a continuously rebalanced hedge makes the option riskless, so its value is the discounted expectation under a risk-neutral measure. Every assumption fails in practice. Volatility is stochastic and clustered, returns have fat tails and jumps, hedging is discrete and costly, and dividends and early exercise matter for American options. The market corrects for this through the implied volatility surface: traders quote a different implied volatility per strike and expiry rather than a single number. Black-Scholes survives as a quoting convention and a way to compute delta, gamma, theta and vega, not as a description of reality."),
    ("Put-call parity", "Put-call parity says that for European options on the same strike and expiry, call minus put equals the forward price minus the strike, discounted: C - P = S - K e^(-rT) after adjusting for dividends. A long call plus short put replicates a forward, so any gap between call and put implied volatilities at the same strike is an arbitrage in theory and a financing or borrow signal in practice. Hard-to-borrow stocks show puts priced richer than calls because short sellers pay a fee that flows into the option market. American options only satisfy parity as an inequality because early exercise breaks the replication. Parity also lets traders read the implied forward, and thus the implied dividend or funding rate, straight from the option chain."),
    ("Delta hedging in practice", "Delta is the option's sensitivity to the underlying price, roughly the probability of finishing in the money for a vanilla option. Delta hedging means holding minus delta shares against a long option so the position is locally insensitive to small moves. In practice the hedge is discrete: rebalance on a time grid, when delta drifts past a band, or when the move exceeds a threshold. More frequent hedging reduces variance of the P&L but raises transaction costs, so hedging bands scale with cost and gamma. The hedged P&L converges to the difference between realized and implied variance, weighted by dollar gamma. Delta hedging cannot remove jump risk, and hedging with the wrong volatility input leaves a path-dependent residual."),
    ("Gamma scalping", "Gamma scalping is the P&L engine of a delta-hedged long option. Gamma is the rate of change of delta, so after a move the position accumulates delta in the direction of the move; rebalancing sells that delta on rallies and buys on dips, locking in small profits that sum to half gamma times the squared move. Those profits are paid for by theta, the daily decay. The trade wins when the realized volatility exceeds the implied volatility the option was bought at. Practitioners choose rebalance rules, from continuous to end-of-day, and the choice changes the variance of outcomes but not the expected value much. Short gamma is the mirror image: collect theta, pay out on large moves, with the loss accelerating as the move grows."),
    ("Theta decay curve", "Theta is the option's daily loss of value from the passage of time, all else equal. For an at-the-money option, value scales with the square root of time to expiry, so decay accelerates as expiry approaches: an option loses roughly half its remaining time value in the last quarter of its life. Out-of-the-money options decay differently, losing most value earlier and flattening near expiry once they are nearly worthless. Theta is largest at the money and near expiry, which is exactly where gamma is largest; the two are two sides of one coin. Sellers who chase high theta in short-dated options are taking on high gamma, so a quiet week of income can be erased by one day's move. Weekend decay is partly priced in before Friday's close."),
    ("Vega and volatility exposure", "Vega is the change in option value per one-point change in implied volatility. It is largest for at-the-money options and grows with time to expiry, roughly with the square root of time, so long-dated options are the cleanest way to express a view on volatility level while short-dated options express views on realized moves. A position's net vega tells you how it behaves when the market reprices risk: short vega positions lose when fear rises even if the underlying has not moved. Vega across expiries is not one number because the term structure shifts unevenly; traders bucket vega by expiry and by strike. Implied volatility and the underlying are negatively correlated in equities, so short vega and long delta compound each other in selloffs."),
    ("Rho and interest rate sensitivity", "Rho measures the change in option value for a one-point change in the interest rate. Higher rates raise call values and lower put values because the strike is paid or received later and the forward rises. Rho is small for short-dated options and grows with maturity, so it matters most for LEAPS, long-dated index options and stock replacement strategies, where a two-point move in rates can shift call prices by several percent. In the zero-rate era rho was ignored; in higher-rate regimes the cost of carry embedded in long-dated calls became a visible drag. Dividends act like a negative rate for calls. Options on futures have near-zero rho because the futures price already embeds carry."),
    ("Vanna, charm and vomma", "Second-order Greeks describe how the first-order Greeks drift. Vanna is the change in delta per unit change in implied volatility, or equivalently the change in vega per unit move in the underlying; it is largest for out-of-the-money options and drives the flows that dealer positioning narratives invoke. Charm is delta decay, the change in delta as time passes, which forces hedgers to trade near expiry even in a flat market. Vomma is the convexity of vega, the change in vega as volatility changes, and explains why far out-of-the-money options gain vega as fear rises. These cross-Greeks matter mostly for large portfolios and market makers; a retail trader mainly needs to know that skew, time and volatility shifts change delta hedges in predictable directions."),
    ("Implied volatility surface", "The implied volatility surface maps strike and expiry to the volatility that makes Black-Scholes reproduce the market price. In equity indices it slopes downward across strikes, so puts trade at higher implied volatility than calls, and it slopes across expiries in a term structure that is usually upward in calm markets and inverted in stress. The surface is usually parameterized in delta or moneyness rather than raw strike so it is comparable across time. Arbitrage-free surfaces satisfy calendar and butterfly constraints; models such as SVI, SABR and Heston fit them. Traders read the surface for relative value, hedge with surface Greeks, and use it to mark positions. A single implied volatility number hides most of what the surface says."),
    ("Volatility skew and term structure", "Skew is the difference in implied volatility between out-of-the-money puts and calls at the same expiry, often quoted as the 25-delta risk reversal or the put-call implied volatility spread. Equity index skew is persistently negative because crashes are sudden and investors pay for downside insurance; single stocks show flatter or even positive skew around takeover or earnings speculation. Term structure is implied volatility across expiries; a normal upward slope reflects uncertainty about distant vol plus a risk premium, while inversion signals near-term fear. Skew steepens in selloffs and flattens in melt-ups. Trading skew means selling rich wings against cheaper strikes and hedging delta, and the risk is that skew is rich for a reason: it pays out precisely in crashes."),
    ("Why the volatility smile exists", "The smile is the pattern that implied volatility is lowest near the money and rises for far strikes. Before the 1987 crash equity index implied volatility was flat across strikes; afterwards the market permanently priced a downside skew. Explanations combine fat-tailed and jump-prone returns, stochastic volatility that correlates negatively with price, supply and demand for crash protection from institutions, and dealer inventory constraints that make far wings expensive to hedge. In currencies the smile is more symmetric; in commodities it can be positively skewed because supply shocks spike prices upward. The smile is not a mispricing to arbitrage; it is the market's replacement for Black-Scholes' constant volatility, and any model that ignores it hedges badly."),
    ("Realized versus implied volatility and the variance risk premium", "Implied volatility is the market's price for future variance; realized volatility is what actually happens. In equity indices implied volatility has exceeded subsequent realized volatility roughly 85 percent of the time, by about 3 to 5 volatility points on average, which is the variance risk premium. It compensates sellers for bearing crash risk and for hedging demand from institutions. The premium is harvested by selling options, variance swaps or VIX futures and delta hedging, and it is the return source behind most short volatility funds. The cost is negative skew: steady small gains punctuated by large losses when realized volatility jumps above implied, as in 2008, February 2018, March 2020 and August 2024. The premium is smaller in single stocks and can be negative before scheduled events."),
    ("VIX construction", "The VIX is the 30-day expected volatility of the S&P 500 implied by a strip of SPX options, computed as a variance swap replication rather than from a single at-the-money option. Cboe takes out-of-the-money puts and calls across all strikes with non-zero bids for two expiries bracketing 30 days, weights each option by one over strike squared, sums them into a variance for each expiry, interpolates to exactly 30 days and reports the square root annualized. Because puts dominate the out-of-the-money strip, the VIX is mostly a measure of downside skew demand. A VIX of 20 implies a typical daily move near 1.3 percent. The VIX is not tradable directly; VIX futures and options settle on a special opening quotation of the same formula."),
    ("VIX futures term structure and roll yield", "VIX futures settle to the VIX on expiry but before then they price the market's expectation of the VIX at that date, not the spot value. The term structure is in contango most of the time, with later months priced above spot because volatility is expected to mean-revert upward and because sellers demand a risk premium. Roughly 80 percent of trading days show contango, so a long front-month position bleeds as it rolls toward spot, while short positions earn that roll yield. In stress the curve inverts into backwardation and shorts lose fast, since the front month can double in days. The slope, often summarized as the ratio of front to second month, is one of the most widely used volatility regime signals and a core input for ETP behavior."),
    ("VIX ETPs and Volmageddon", "Exchange-traded products such as VXX, UVXY and SVXY hold a constant-maturity mix of first and second month VIX futures and rebalance daily. Long products decay from contango roll and volatility drag, losing most of their value over years despite occasional spikes; short products earn the roll but face unbounded loss on a spike. On 5 February 2018 the VIX rose over 100 percent in a day, and the inverse products' mandated end-of-day rebalancing forced them to buy roughly 280,000 VIX futures into the close, amplifying the spike. XIV was terminated after losing over 90 percent and SVXY cut its leverage to half. The lesson is that leveraged and inverse volatility products are path dependent, their hedging flows are predictable, and a strategy that looks like steady income can end in one session."),
    ("Covered calls and the buy-write evidence", "A covered call holds stock and sells a call against it, giving up upside above the strike in exchange for premium. Cboe's BXM index, which sells a monthly at-the-money SPX call, has delivered returns close to the S&P 500 with roughly two thirds of the volatility since 1986, so risk-adjusted performance looks attractive, but it underperforms badly in strong bull years and still takes nearly the full loss in crashes. The strategy is short volatility with a long stock bias: its edge is the variance risk premium, not the premium income itself, which is not free money but the fair price of the upside sold. Evidence favors slightly out-of-the-money strikes and monthly rather than weekly cycles for cost reasons. Covered calls on single stocks add idiosyncratic gap risk and assignment complications around dividends."),
    ("Cash-secured puts", "Selling a cash-secured put obligates the seller to buy the stock at the strike if assigned, with cash held against the full obligation. By put-call parity it has the same payoff as a covered call at the same strike, so any belief that one is safer than the other is an illusion; both are long stock exposure with capped upside. The premium is compensation for absorbing downside, and Cboe's PUT index shows returns similar to the S&P 500 with lower volatility over decades, again from the variance risk premium. The classic retail framing of getting paid to buy stock you wanted anyway hides that assignment usually happens after a fall, so the trader buys at a price above market. Sizing should assume assignment on every contract at once in a market-wide drop."),
    ("Vertical spreads", "A vertical spread buys one option and sells another of the same type and expiry at a different strike. Debit spreads cap cost and profit; credit spreads collect premium with a defined maximum loss equal to the strike width minus the credit. The spread's value is bounded, so the Greeks are muted: net vega and gamma are small, and the position is mostly a bet on where the underlying finishes relative to the strikes. A credit put spread sold at 20 delta wins often and loses about four times the credit when it fails, so the win rate of 75 to 80 percent is roughly the fair probability and the edge, if any, comes from skew and the variance risk premium. Spreads reduce margin and tail risk versus naked options at the cost of paying two bid-ask spreads."),
    ("Iron condors and their risk profile", "An iron condor sells an out-of-the-money put spread and an out-of-the-money call spread on the same expiry, collecting premium with defined maximum loss on each side. It profits if the underlying stays inside the short strikes through expiry, so it is short gamma and short vega with near-zero delta at entry. Typical retail structures sell the 15 to 20 delta strikes 30 to 45 days out and collect about a third of the wing width, giving a win rate near 70 percent and a maximum loss of two to three times the credit. The risk profile is a negative-skew distribution: many small wins and occasional large losses concentrated in trending or volatile markets. Adjustments, such as rolling the untested side, add delta risk; the honest evidence is that condors monetize the variance risk premium with high transaction costs and no directional edge."),
    ("Calendar and diagonal spreads", "A calendar spread sells a near-dated option and buys a longer-dated one at the same strike, paying a debit. It is long vega, because the long-dated leg carries more vega, and profits from time decay of the short leg if the underlying stays near the strike. It loses if the underlying moves far in either direction or if the term structure flattens, since the trade is effectively long the back month against the front. Diagonals shift the long leg to a different strike, adding a directional lean; the poor man's covered call is a diagonal with a deep in-the-money LEAPS call against short near-dated calls. Calendars are used before events to sell inflated front-month implied volatility while holding back-month exposure, and around earnings the front month collapses after the print while the back month barely moves."),
    ("Straddles and strangles around events", "A long straddle buys a call and a put at the same strike, a strangle buys them at different strikes; both profit from a large move in either direction and lose theta if nothing happens. Before earnings, elections or central bank decisions, implied volatility in the expiry covering the event rises to price the expected jump, so buying the straddle pays a fair or rich price and the trade only wins if the realized move exceeds the implied move. Selling the straddle collects the inflated premium and profits from the post-event implied volatility crush, but takes unlimited loss on a surprise. Studies of single-stock earnings show sold straddles earning a small average premium with fat-tailed losses; delta hedging the straddle turns it into a purer bet on realized versus implied movement rather than direction."),
    ("Earnings implied move", "The implied move is the market's expected magnitude of the stock move through an event, read from the option chain. The quick estimate is the price of the at-the-money straddle in the expiry just after the event divided by the stock price, or about 85 percent of that straddle for a one standard deviation move. A more careful method strips the event variance out of the term structure by comparing the front expiry's implied variance with a later expiry's, since the difference in total variance is the event's contribution. A stock trading at 100 with a 6 dollar straddle implies roughly a 5 percent expected move. Comparing the implied move with the stock's historical earnings moves shows whether options are pricing the event richly or cheaply, which is the only real edge in earnings option trades."),
    ("Zero-days-to-expiry options", "0DTE options expire the same day and now make up around half of SPX option volume, driven by daily expirations and retail lottery demand. They have almost no vega and enormous gamma: an at-the-money 0DTE contract can move from a fraction of a point to several points in minutes, and its delta swings from near zero to near one. Sellers collect fast theta and win a high fraction of days but face intraday moves that can wipe out weeks of premium; buyers pay a large volatility premium and lose on most days. Research finds that 0DTE implied volatility is systematically high relative to realized and that gamma hedging flows from these contracts can add intraday momentum near strikes late in the session. Sizing 0DTE positions by premium collected rather than by notional exposure is the common fatal error."),
    ("Gamma exposure and dealer positioning narratives", "Gamma exposure, or GEX, estimates the aggregate gamma held by option dealers from open interest, assuming dealers are short customer puts and long customer calls. If dealers are net long gamma they hedge by selling rallies and buying dips, which dampens volatility; if net short gamma their hedging chases moves and amplifies volatility. The narrative has real mechanics behind it, and academic work on 0DTE and expiry-day pinning supports some dampening effects, but the sign of dealer positioning is inferred rather than observed, open interest does not reveal who holds what, and much index gamma sits in structured products and dealers' own books. GEX levels are widely published and can become self-fulfilling for intraday support and resistance, yet their predictive value in backtests is modest and regime dependent. Treat GEX as context, not as a signal."),
    ("Pin risk and early assignment", "Pin risk is the uncertainty at expiry when the underlying closes near a short strike: the seller does not know until after the close whether they will be assigned, so they may wake up with an unwanted stock position and no hedge. American-style equity options can be assigned early at any time; this happens mainly to deep in-the-money calls the day before an ex-dividend date when the dividend exceeds the remaining time value, and to deep in-the-money puts when the interest on the strike exceeds the put's extrinsic value. Index options like SPX are European and cash settled, avoiding both problems. Spreads with a short in-the-money leg can be assigned while the long leg remains, creating margin calls. Closing short in-the-money legs before expiry costs a little and removes the tail."),
    ("Options on futures and SPAN margin", "Options on futures, such as ES options on S&P 500 futures, settle into a futures position rather than stock and are margined by SPAN, the clearinghouse system that scans a set of price and volatility scenarios and charges the worst-case one-day loss for the whole portfolio. SPAN recognizes offsets between futures and options, so a covered position or a spread posts far less than the sum of its legs. Margin can jump overnight when the exchange raises scenario ranges in stress, forcing liquidation at the worst time. Futures options trade nearly 24 hours, have quarterly and weekly expiries, use a multiplier tied to the futures contract, and in the United States receive 60/40 tax treatment under Section 1256. Liquidity is concentrated in front months and round strikes."),
    ("Portfolio margin", "Portfolio margin replaces the fixed strategy-based Regulation T rules with a risk-based calculation: the broker stresses the whole portfolio across a range of underlying moves, typically plus or minus 15 percent for broad indices and larger for single stocks, and requires margin equal to the worst loss. Hedged option portfolios can hold several times more notional than under Reg T, which is why professional sellers use it. The danger is that the stress range is calibrated to normal markets; a move beyond the tested range creates losses far larger than the margin held, and brokers raise house requirements in crises, forcing sales into falling markets. Eligibility usually needs six figures of equity and an options approval level. Portfolio margin amplifies both the return and the ruin probability of short volatility strategies."),
    ("Volatility forecasting with GARCH and HAR-RV", "Volatility is forecastable because it clusters. GARCH models tomorrow's variance as a weighted sum of a long-run level, yesterday's squared return and yesterday's variance, with the two weights typically summing to about 0.98 so shocks decay slowly. HAR-RV instead regresses next-day realized variance on daily, weekly and monthly averages of past realized variance computed from intraday data, and usually beats GARCH out of sample because intraday data measure variance more precisely. Both forecast the level of volatility better than they forecast changes, and both lag turning points. Implied volatility from options is itself a strong forecast because it embeds the crowd's information, so the useful trading signal is the gap between a statistical forecast and implied, adjusted for the usual variance risk premium."),
    ("Volatility targeting for options sellers", "Option sellers face exposure that grows precisely when volatility rises: the same number of contracts carries more dollar gamma and vega in a high-volatility regime. Volatility targeting sizes positions so that the expected daily P&L swing stays constant, cutting contract counts when implied or realized volatility rises and raising them when it falls. A practical rule sizes short premium so that a two or three standard deviation move, measured by the current implied volatility, costs a fixed fraction of equity such as 2 to 5 percent. This trims exposure automatically ahead of crises, because implied volatility usually climbs before the worst days. The evidence for volatility-scaled short option strategies shows higher Sharpe ratios and shallower drawdowns than fixed-size selling, at the cost of lower returns in long calm periods."),
    ("Tail risk of short volatility and sizing", "Short volatility strategies earn a steady premium and lose in rare, large jumps, so their return distribution has a fat left tail that standard deviation hides. A strategy that collects 1 percent a month can lose 30 percent in a week when implied volatility triples and the underlying gaps; history shows this in October 1987, 2008, February 2018 and March 2020. Sizing must assume the loss at the tail, not the average day: compute the loss at a move of three to four implied standard deviations plus an implied volatility doubling, and keep that number inside the drawdown you can survive. Defined-risk structures, long far wings, position limits per expiry and a hard cap on net short vega are the practical tools. The honest expectation is that a short volatility book will one day hit its worst historical loss again."),
    ("The Kelly problem for option sellers", "The Kelly criterion sizes bets to maximize long-run growth given win probability and payoff, but for option sellers the inputs are unreliable in the way that matters most. A short put spread with an 80 percent win rate and a four-to-one loss ratio has a Kelly fraction near zero, and any error in the estimated tail probability moves it negative. Backtests understate the tail because the sample contains few crashes, and losses cluster, so consecutive losing months are more likely than independence assumes. Practitioners therefore use a small fraction of Kelly, often a quarter or less, size by the stress loss rather than the average, and accept that the estimated edge is uncertain. Over-betting a positive-expectancy short volatility strategy is the most common way it ends in ruin."),
    ("Delta-neutral volatility trading and the gamma-theta P&L", "A delta-hedged option position has a daily P&L that is approximately half gamma times the squared price move minus the theta paid, plus vega times the change in implied volatility. In volatility terms this is half dollar gamma times the difference between realized variance for the day and the implied variance the option was priced at. Long gamma profits when the realized move exceeds the implied daily move, roughly implied volatility divided by 16 as a percent; short gamma profits when the market is quieter than implied. The sum over the option's life is the realized-minus-implied variance weighted by the path of dollar gamma, so where the underlying spends its time matters. This formula is the basis for gamma scalping, variance swaps and every implied-versus-realized volatility trade."),
    ("Dispersion and correlation trading", "Index implied volatility is usually rich relative to the volatility implied by its components, because index options carry a correlation risk premium: investors pay for protection against everything falling together. Dispersion trading sells index options and buys options on the constituents, delta hedging each leg, and profits when realized correlation among stocks is lower than the correlation implied by the price gap. The position is short correlation and roughly vega neutral. It earns steadily in calm, stock-picking markets and loses when a macro shock drives correlations toward one, so its return profile resembles other short volatility trades. Implementation demands many legs, high transaction costs and careful weighting, so it is mostly an institutional strategy; retail traders can see the same premium by comparing a stock's implied volatility with the index's."),
    ("Crypto options on Deribit", "Deribit dominates bitcoin and ether option volume with European, cash-settled contracts that are margined and paid in the underlying coin, so the option's value and the collateral move together and a short call loses faster in coin terms during a rally. Implied volatility typically sits between 40 and 100 percent, far above equities, and the skew flips sign with sentiment, showing call skew in bull runs rather than the permanent put skew of equity indices. Expiries cluster on Fridays at 08:00 UTC and monthly and quarterly expiries concentrate open interest, creating max pain narratives. There is no central clearing or regulator of last resort, so counterparty and platform risk are part of the trade. The variance risk premium exists in crypto but is more volatile, and liquidity thins fast away from at-the-money strikes."),
    ("LEAPS and stock replacement", "LEAPS are long-dated options with expiries of one to three years. A deep in-the-money LEAPS call with delta near 0.8 or higher behaves like stock for a fraction of the capital, so it is used for stock replacement: the trader controls the same upside while risking only the premium and freeing cash. The costs are the extrinsic value paid, which decays slowly early and faster in the final months, the embedded financing at the implied interest rate, and forgone dividends. Because LEAPS have large vega and rho, they gain when implied volatility or rates fall after purchase and lose otherwise. Leverage through LEAPS is more forgiving than margin, since the loss is capped at the premium, but that cap is 100 percent of the money committed."),
    ("Protective puts and collars", "A protective put buys a put against a long stock or index position, capping downside below the strike at the cost of premium. Rolling puts continuously is expensive because of skew and the variance risk premium: long-run studies of monthly 5 percent out-of-the-money SPX puts show a drag of several percent per year that usually exceeds the losses avoided, so constant put buying is a poor long-term hedge. A collar finances the put by selling a call, giving up upside above the call strike; a zero-cost collar sets strikes so the premiums match and turns equity into a bounded return band. Collars work well for concentrated stock positions and for tax or regulatory reasons. Puts work best as tactical hedges bought when implied volatility is low, sized to survive a specific scenario, rather than as permanent insurance."),
    ("Rolling and adjusting positions", "Rolling closes an option position and opens a similar one at a later expiry or different strike. Rolling out in time collects more premium and gives the trade room, rolling up or down moves the strike, and rolling for a credit is only possible when the new option is richer than the one being closed. Adjustment rules often trigger when the short strike is tested, when delta exceeds a band or when the loss reaches a multiple of the credit. Each roll pays a new bid-ask spread and often converts a small defined loss into a larger, longer-lived position, which is why serial rolling can turn a manageable loser into a blowup. The honest view is that adjustment logic manages variance and psychology more than it adds expected value; a rolled position should be judged as a fresh trade."),
    ("Options liquidity, spreads and fill quality", "Option markets are wide: even SPX options quote spreads of several ticks and single-stock options can quote 10 to 20 percent of the option's value. Because a typical retail strategy trades many legs and rolls often, paying the spread is usually the largest cost and can exceed the theoretical edge. Fill quality improves by working limit orders near the midpoint, trading liquid underlyings and standard expiries, avoiding the first and last minutes of the session, and using complex order books for spreads rather than legging. Open interest and volume at the strike, the spread relative to the option's vega and the depth shown on exchanges all measure liquidity. Payment for order flow means retail orders often fill inside the quoted spread, but the improvement is smaller for multi-leg orders and illiquid names."),
    ("Options tax and regulatory notes", "Tax treatment differs by instrument and jurisdiction. In the United States, broad-based index options such as SPX, and options on futures, fall under Section 1256, taxed 60 percent long-term and 40 percent short-term regardless of holding period and marked to market at year end; equity and ETF options are taxed as ordinary capital gains and are subject to wash-sale rules and to straddle rules that can defer losses on hedged positions. Regulation T sets margin for retail accounts, brokers assign options approval levels, and the OCC's Characteristics and Risks of Standardized Options must be delivered before trading. Pattern day trading rules apply to option round trips. European and UK retail traders face different product rules and cannot easily access some US ETPs. None of this changes expected value, but it changes what a trader keeps."),
    ("Retail option-selling myths assessed", "Several popular claims deserve scrutiny. That most options expire worthless is misleading: many are closed early, and expiring worthless says nothing about the seller's P&L along the way. That selling 30 to 45 day options at 16 delta yields a 70 percent win rate is true but is roughly the fair probability, not an edge. That premium income is like rent ignores that the income is compensation for a loss distribution with a fat left tail. That managing at 50 percent of max profit improves results is partly supported, mainly because it cuts gamma exposure near expiry. That implied volatility rank identifies rich premium has some support since the variance risk premium is larger when implied volatility is high, but high implied volatility also precedes the largest losses. The durable edge is the variance risk premium, and it is earned by surviving."),
]

SOURCES = {
    "feeds": [
        "https://quantpedia.com/feed/",
        "https://vixandmore.blogspot.com/feeds/posts/default?alt=rss",
        "https://www.cboe.com/rss/default.aspx",
        "https://www.macroption.com/feed/",
        "https://moontowermeta.com/feed/",
        "https://www.sixfigureinvesting.com/feed/",
    ],
    "subreddits": ["options", "thetagang", "VolatilityTrading", "Vitards", "quant"],
    "github_queries": [
        "topic:options-trading",
        "topic:volatility",
        "implied volatility surface python",
        "options greeks black scholes library",
        "vix futures term structure backtest",
    ],
    "arxiv_topics": [
        "implied volatility surface",
        "variance risk premium",
        "0DTE options",
        "dealer gamma exposure",
        "realized volatility forecasting HAR",
    ],
    "urls": [
        "https://www.optionseducation.org/",
        "https://www.optionseducation.org/optionsoverview/getting-started-with-options",
        "https://www.theocc.com/company-information/documents-and-archives/options-disclosure-document",
        "https://www.cboe.com/optionsinstitute/learningportal",
        "https://www.cboe.com/optionsinstitute/research",
        "https://www.cboe.com/tradable-products/vix/",
        "https://cdn.cboe.com/resources/index_values/2021/Cboe-VIX-White-Paper-Methodology-Addendum.pdf",
    ],
}
