"""Knowledge pack: trading psychology, process, and lessons from market history and great traders.

Every lesson states a finding or event, the public numbers where they exist, and
the practical lesson a trader should take. Quotes are paraphrased, never invented.
"""

from __future__ import annotations

DOMAIN = "Trading psychology, process and market history"

LESSONS: list[tuple[str, str]] = [
    ("Loss aversion and the disposition effect in trading data", "Terrance Odean's 1998 study of about 10,000 discount brokerage accounts from 1987 to 1993 measured the disposition effect directly: investors realized 14.8% of available paper gains but only 9.8% of available paper losses, so they were about 50% more likely to sell a winner than a loser. The pattern reversed only in December, when tax-loss selling dominated. It was costly: the losers they kept underperformed the winners they sold by around 3.4% over the following year. The mechanism is loss aversion, the pain of a realized loss outweighing an equal gain. The practical answer is a stop loss and a winner exit rule set before entry, so that closing a trade is a rule event rather than a decision made while feeling the loss."),
    ("Overtrading and the evidence on retail trader returns", "Barber and Odean's 2000 paper Trading Is Hazardous to Your Wealth studied 66,465 households at a discount broker from 1991 to 1996. The most active fifth earned 11.4% a year against a market return of 17.9%, with the gap almost entirely transaction costs; men traded 45% more than women and earned about a percentage point less for it. A Brazilian study of everyone who began day trading index futures in 2013 to 2015 found that 97% of those who persisted beyond 300 days lost money, only 1.1% earned above the minimum wage, and there was no evidence of learning. European regulators in 2018 reported that 74% to 89% of retail CFD accounts lose money. Turnover is a certain cost and an edge only sometimes, so every trade must clear its expected value hurdle after costs."),
    ("Revenge trading and tilt", "Tilt is the poker term for playing worse because of emotion, and revenge trading is its trading form: after a loss the trader re-enters quickly, often larger, to win the money back. Coval and Shumway's study of Chicago Board of Trade proprietary traders found that those with morning losses took significantly more risk in the afternoon, and that the extra risk lowered their results. The pattern turns one bad trade into a bad day and a bad day into a drawdown. The defense must be a rule, because in the moment the next trade always feels justified: a daily loss limit in R or percent of equity, a stop after two or three consecutive losses, and a mandatory pause after any rule violation. Position sizing that keeps each loss small removes most of the fuel."),
    ("The trading journal and what to record", "A trading journal lets a trader measure their behavior rather than remember it. The minimum record per trade is date and time, instrument, the named setup, planned entry, stop and target, position size and initial risk in currency, realized result in R multiples, market regime, and a one-line thesis. Add the emotional state before entry, whether every rule was followed, a mistake tag such as chased, moved stop, oversized or early exit, and a chart screenshot. Reviewed weekly, the journal answers what P&L alone cannot: which setups have positive expectancy, whether discretionary overrides help or hurt, when losses cluster, and which mistakes repeat. Separating good decisions from good outcomes is its central purpose, and it is the raw material for every other process rule."),
    ("Pre-trade checklists", "A pre-trade checklist moves the decision from the hot state, with price moving and money at stake, to the cold state in which the rules were written. Aviation and surgery adopted checklists because expert errors are mostly omissions under pressure, and trading errors are the same. Typical items: the setup matches a playbook entry, the stop sits where the thesis is wrong, size is computed from stop distance and the risk budget, the position is not correlated with existing exposure, no earnings or central bank event falls inside the holding period, spread and liquidity are acceptable, the daily loss budget is not exhausted, and the trader is rested. A trade failing any item is skipped and logged, so the rule itself can be tested later."),
    ("The playbook concept", "A playbook, a term popularized by proprietary trading firms, is a written catalogue of the setups a trader is allowed to take. Each entry describes the market conditions in which it appears, the exact trigger, stop placement, exit logic, position size, chart examples, and the setup's statistics from the journal: trade count, win rate, average R and expectancy. New traders master one or two setups before adding more, because edge per setup can only be measured with enough trades. The playbook also defines what is not a trade, which removes most boredom and FOMO entries. Setups whose expectancy decays over rolling windows are retired, the same way a systematic trader monitors signal decay."),
    ("Process goals versus outcome goals", "An outcome goal is to make a certain amount this month; a process goal is to follow the entry, stop and sizing rules on every trade and journal each one. In the short run outcomes are dominated by noise: a strategy with a 45% win rate and positive expectancy produces losing weeks routinely, so grading by outcome punishes correct behavior and rewards lucky rule breaking. Process goals are controllable and compound into outcomes through the law of large numbers. Sports psychology and Brett Steenbarger's coaching both frame trading this way: score each trade on adherence and let the equity curve be the aggregate. The trap runs the other way too, when a winning trade that broke the rules teaches the trader that rules are optional."),
    ("Handling drawdowns psychologically", "Every strategy has drawdowns, and the trader who does not expect them abandons the method at the worst point. Their size can be estimated in advance: with a 40% win rate, runs of eight or more consecutive losses are routine over a thousand trades, and a backtested maximum drawdown should be assumed to roughly double live. Pre-committed rules remove the decision from the emotional moment: halve size after a 10% drawdown, stop and review after 20%, and change the system only if evidence shows the edge has decayed rather than that variance has arrived. Records of past drawdowns and recoveries anchor the mind. The real risk in a drawdown is losing the discipline that produced the edge, and the commonest error is oversizing to recover quickly."),
    ("Confidence calibration and the forecast log", "Calibration means that events a person calls 70% likely happen about 70% of the time. Studies of experts across fields show heavy overconfidence: 90% confidence intervals contain the truth roughly half the time. A forecast log fixes this for a trader. Before each trade or market call, write the probability assigned and the horizon, then score it with a Brier score, the mean squared error between forecast and outcome. Within a few dozen entries the log shows whether high conviction trades actually win more often than ordinary ones; if not, sizing by conviction adds risk with no edge and should stop. Philip Tetlock's forecasting research found that calibration improves with feedback, granular probabilities and willingness to update, the same discipline a journal enforces."),
    ("Confirmation bias and social media", "Confirmation bias is the tendency to seek and weigh evidence that supports an existing position and discount evidence against it. Social media amplifies it: after buying, a trader reads the bullish threads, follows accounts that agree, and sees the chart as confirming the thesis. Barber, Huang, Odean and Schwarz found that episodes of intense herding by Robinhood users into the same stocks were followed by negative abnormal returns of around 5% over the next month. Defenses: write the thesis and the disconfirming evidence that would exit the trade before entry, run a pre-mortem asking why the trade failed, mute commentary while in a position, and track in the journal how trades taken after reading a thread perform. Crowd enthusiasm is more often a contrarian sentiment signal than a confirmation."),
    ("FOMO and chasing", "Fear of missing out drives entries after a move has already extended, the worst place for reward to risk because the stop must be far away and the easy part of the move is over. Barber and Odean showed in All That Glitters that individual investors are net buyers of attention-grabbing stocks, those with extreme returns, high volume or news, and that this buying does not earn excess returns. A chased entry typically delivers a fraction of the R multiple of a planned one for the same setup. The cure is procedural: entry price and invalidation level are defined before the move, and if price has passed the entry, the trade is missed and costs nothing. A journal column for chased trades usually shows negative expectancy, which makes the rule easier to obey."),
    ("The sunk cost fallacy in position management", "A sunk cost is money already lost that no future decision can recover, yet traders anchor on their entry price and manage positions to get back to even. The result is averaging down into losers, widening stops, and holding a broken thesis because closing would make the loss real. Nick Leeson's losses at Barings in 1995, about 827 million pounds, grew from repeatedly doubling positions to recover earlier losses, and most trading-firm blowups follow the same escalation of commitment. The market does not know the entry price. The test at every review is whether the trader would open this position, at this size, at the current price with fresh capital; if not, the correct size is smaller or zero. Adding is legitimate only as planned pyramiding of a winner, never as rescue of a loser."),
    ("Boredom trading", "Most of a session, and most days in a swing trading calendar, contain no valid setup, and the discomfort of doing nothing pushes traders into low-quality trades taken for stimulation. These trades are marginal by construction, since they are the ones the playbook excluded. Their cost is not only negative expectancy but that a boredom loss often triggers revenge trading. Journals that tag the reason for each entry consistently show that trades outside defined setups lose money, matching the retail overtrading studies. Remedies include a fixed maximum number of trades per day, research or exercise scheduled into dead periods, and, for many people, moving toward a systematic approach in which the code decides and boredom has nowhere to act."),
    ("Routine, sleep and physical state", "Trading decisions are made by a body, and its state changes risk preferences. Sleep deprivation studies using gambling tasks show that a night without sleep increases risk taking and reduces sensitivity to losses, the worst possible profile for a trader. Alcohol, illness, anger from outside life and hunger have similar effects. Brett Steenbarger treats physical routine as a performance variable: consistent sleep, exercise, a pre-market routine that reviews levels and scheduled events, and a post-market review at a fixed time. Pilots and surgeons are grounded when impaired, and a trader should apply the same rule: after poor sleep or emotional upheaval, size down or do not trade. The journal's emotional state column lets the trader verify from their own data how much state affects results."),
    ("Sizing for sleep: the sleep test", "The old Wall Street advice to sell down to the sleeping point is a position sizing rule in disguise. If a position keeps the trader awake or checking prices compulsively, it is too large for their risk tolerance, whatever the Kelly formula says. The cost of oversizing is not only the potential loss but the degraded decisions it produces: early exits from winners, frozen stops, and inability to think about the next trade. The practical version is to estimate the worst plausible adverse move, such as an overnight gap of three times ATR or a 30% earnings gap, and confirm that the loss is tolerable financially and emotionally. Volatility targeting and fractional Kelly give the mathematical ceiling; the sleep test gives the personal one, and the smaller is correct."),
    ("When to stop trading: rules for a break", "A stop-trading rule is a circuit breaker for the trader, analogous to the exchange circuit breakers introduced after 1987 and 2010. Common triggers are a daily loss of 2R to 3R or 1% to 2% of equity, three consecutive losses, any rule violation such as a moved stop, a drawdown beyond a preset threshold, and life events such as illness or a major financial change. Proprietary firms enforce daily loss limits mechanically because losses after the limit are far worse per trade than losses before it. The break is defined in advance, from the rest of the day to a week or more, and the return is at reduced size. The purpose is not punishment: the edge exists only while the trader executes the process, and after these triggers they usually are not."),
    ("Discretionary and systematic temperaments", "Discretionary traders make each decision from rules plus judgment; systematic traders research rules, code them, and let the system execute. Market Wizards include both, so neither is inherently superior, but they suit different people. Discretionary trading rewards fast pattern recognition, tolerance for ambiguity and calm in the moment; systematic trading rewards patience for research, statistical thinking and the ability to follow a system through a drawdown without interfering. Evidence on hybrids is unfavorable: studies of discretionary overrides of systematic signals, including at CTAs, generally find the overrides reduce returns. Choose by failure mode. A trader whose journal shows losses from impulsive entries belongs nearer the systematic end; one whose backtests never survive live trading may be a better discretionary trader than researcher."),
    ("From paper trading to live: the psychological gap", "Paper trading tests logic, not the trader. Simulated fills are optimistic, there is no slippage or partial fill, and above all no money at risk, so the emotional interference that causes most real losses is absent. Traders who jump from paper to full size routinely see performance collapse and blame the strategy. The better path is to go live at the smallest possible size, a single share or a micro futures contract, so the trade is real but the loss trivial, and to compare live results with paper results over the same period. The difference isolates execution and psychology from the edge itself. Only when the live process matches the paper process over dozens of trades should size rise, the same principle as running a new model with tiny capital before allocating."),
    ("Scaling up size gradually", "Each meaningful increase in position size feels different, and traders who double size after a good month often find the same setups suddenly produce hesitation and early exits. Size should scale with demonstrated process, not with recent P&L. A common rule is to increase only after a fixed number of trades, say 30 to 50, executed with full rule adherence at the current size, and to increase in steps of 25% to 50% rather than doubling. A drawdown or a run of rule violations resets size to the previous level. This is anti-martingale sizing, growing exposure after evidence rather than after losses, and it mirrors fixed fractional position sizing, where size grows with equity. Druckenmiller-style pressing when conviction and results align is the advanced version, appropriate only after years of calibrated records."),
    ("Trading as a business", "Treating trading as a business starts with an honest accounting of costs: data, platform and charting subscriptions, commissions and spreads, hardware, education, and taxes, which on short-term gains are ordinary income in many countries. Fixed costs of 3,000 a year on a 50,000 account impose a 6% hurdle before any profit, more than most strategies deliver net. A business keeps records for taxes and performance review, has a written plan with strategies and risk limits, a capital account separate from the household emergency fund, and a runway of living expenses that does not depend on trading income. Most importantly it has a go or no-go review at a fixed date: does the record show positive expectancy after costs, or should the capital go into an index fund. Businesses that never ask are hobbies with expensive losses."),
    ("Realistic return expectations with numbers", "The long-run return of the US stock market is about 10% a year nominal with roughly 16% volatility. The best records over decades are around 20% a year for Warren Buffett and about 30% for Soros's Quantum Fund,; the Medallion Fund's reported 39% net is unique and unverifiable. A retail trader compounding 15% to 25% a year with a Sharpe ratio near 1 is doing exceptionally well. On a 10,000 account that is 2,000 a year, not a living, which is why capital rather than skill is the usual constraint. Claims of 10% a month compound to 214% a year and would turn 10,000 into a billion in about 13 years; that no such record exists is the proof the claim is false. Expect the first years flat or negative."),
    ("Jesse Livermore's rules and his end", "Jesse Livermore, 1877 to 1940, is the trader behind Reminiscences of a Stock Operator and the author of How to Trade in Stocks. He made fortunes shorting the 1907 panic and the 1929 crash, reportedly around 100 million dollars in 1929, and went bankrupt several times in between. His rules, paraphrased: trade in the direction of least resistance, wait for the market to confirm before committing, pyramid winners rather than averaging losers, cut losses quickly, and recognise that the big money is made by sitting through a trend rather than by frequent trading. These are the core of trend following and position sizing. He broke his own rules repeatedly, lost his last fortune in the 1930s, and died by suicide in 1940. A real edge does not protect against poor risk management and psychological instability; survival is a separate skill from brilliance."),
    ("Richard Dennis and the Turtle experiment", "In 1983 and 1984 Richard Dennis, a Chicago futures trader, settled a debate with partner William Eckhardt about whether trading could be taught by training about two dozen novices for two weeks and giving them capital. The Turtle rules were a complete trend following system: Donchian breakouts of 20 and 55 days, size of one percent of equity per unit of volatility N, an ATR-like range, stops at two N, pyramiding to a maximum number of units, and limits on correlated exposure. The group reportedly earned around 175 million dollars over five years. The lesson has two sides: rules can be taught and the edge was real, but several trainees could not follow them through losing streaks, and Dennis's own public funds lost around 50% in 1987 and 1988 and closed. Discipline was the scarce resource."),
    ("Ed Seykota's principles", "Ed Seykota built one of the first computerized trend following systems in the early 1970s and, according to his Market Wizards interview, one client account grew by roughly 250,000% over 16 years. His principles as paraphrased there: cut losses, ride winners, keep bets small, follow the rules without question, and know when to break the rules, the last offered with a wink because the first four matter most. He also argued that everyone gets what they want out of the market, meaning repeated losses usually serve some psychological need such as excitement or self-punishment, an idea he later developed in his Trading Tribe work on feelings. A simple long-term trend following system, mechanically executed with small position sizing across many markets, was enough; the trader's job was to stay out of its way."),
    ("Paul Tudor Jones and the 1987 crash", "Paul Tudor Jones anticipated the October 1987 crash partly through his analyst Peter Borish's overlay of the 1980s market on the 1920s and through his reading of portfolio insurance, which would force selling into a decline. On 19 October 1987 the Dow fell 22.6% in a single day, and the Tudor Futures Fund reportedly returned well over 100% for the year. His principles, paraphrased from Market Wizards: play defense not offense, never average a losing position, look for trades where the potential reward is several times the risk, and after a losing streak cut size sharply until rhythm returns. The lesson is asymmetry: find a scenario where the downside is capped by a stop and the upside is a regime change, size for the stop, and let the tail do the work."),
    ("George Soros, reflexivity and the 1992 pound trade", "George Soros's theory of reflexivity holds that prices do not merely reflect fundamentals but change them: rising prices improve credit and confidence, which justify higher prices, until the loop reverses. He applied it in September 1992 when the pound was pinned in the European Exchange Rate Mechanism at a level British fundamentals, a recession against high German rates after reunification, could not sustain. The Quantum Fund, run day to day by Stanley Druckenmiller, shorted about 10 billion dollars of sterling; on 16 September, Black Wednesday, Britain left the mechanism and the fund made roughly a billion dollars. The trade was asymmetric: if the peg held the loss was small carry, if it broke the gain was large. Soros has written that he is wrong often and that his results come from correcting errors quickly, which puts risk management above forecasting."),
    ("Stanley Druckenmiller on concentration and being wrong fast", "Stanley Druckenmiller ran Duquesne Capital for three decades with reportedly about 30% annual returns and no losing year, and managed the Quantum Fund for Soros from 1988 to 2000. His approach, from his public talks, was to make few bets, put a large share of capital into those with the highest conviction, and watch them closely rather than diversify into ideas he liked less. The counterpart was speed in admitting error: exit fast, without waiting for the loss to prove itself. He has said openly that in early 2000 he bought technology stocks near the top after being correctly bearish, losing around three billion dollars for Quantum because he could not stand watching others make money, and that the mistake was emotional, not analytical. Concentration works only with that exit discipline and sizing that survives being wrong."),
    ("Jim Simons and Renaissance Technologies", "Jim Simons, a mathematician and codebreaker, founded Renaissance Technologies in 1982 and hired physicists, statisticians and computer scientists rather than finance people. Its Medallion Fund, closed to outsiders since 1993 and capped near ten billion dollars, reportedly returned about 66% a year gross and 39% net from 1988 to 2018 after fees of 5% of assets and 44% of profits, figures from Gregory Zuckerman's reporting, never publicly audited. What is known of the method: enormous cleaned datasets, many small statistical edges with a hit rate only slightly above 50%, very high turnover, heavy leverage, and rigorous execution research. Renaissance's public funds for outside investors have done far worse, showing the edge is capacity constrained. Medallion is evidence that markets are exploitable with infrastructure and rigor, not a template a retail account can copy."),
    ("Nassim Taleb, antifragility and the barbell", "Nassim Taleb's books, from Fooled by Randomness to The Black Swan and Antifragile, argue that returns have fat tails, that rare events dominate long-run outcomes, and that risk measures built on normal distributions understate them. Antifragile means benefiting from volatility rather than merely surviving it. His barbell puts most capital, around 85% to 90%, in very safe assets and the rest in highly convex bets such as long out-of-the-money options, so the worst case is capped while the upside stays open. The cost is steady bleeding from theta in calm markets, which is why tail hedging funds show long stretches of small losses and rare enormous gains, as in 2008 and March 2020. The lessons: avoid strategies that collect small premiums in front of ruin, such as naked short volatility, size for the worst day rather than the average, and prefer payoffs convex to surprise."),
    ("Long-Term Capital Management 1998 as a leverage lesson", "Long-Term Capital Management (LTCM), founded by John Meriwether with Nobel laureates Myron Scholes and Robert Merton on its board, ran convergence trades in bonds and swaps that earned around 40% a year in 1995 and 1996. By 1998 about 4.7 billion dollars of equity supported roughly 125 billion of assets, leverage above 25 to 1, plus derivatives with notional value above a trillion dollars. After Russia defaulted in August 1998, spreads its models said should converge widened everywhere at once, and the fund lost about 4.6 billion dollars in under four months. The Federal Reserve brokered a 3.6 billion dollar rescue by fourteen banks. The lessons: correlations across supposedly independent trades go to one in a crisis, liquidity vanishes when needed, models fitted to calm data understate tails, and leverage turns a temporary mark-to-market loss into permanent ruin."),
    ("The dot-com bubble and its lessons", "The Nasdaq Composite rose from about 1,000 in 1995 to a peak of 5,048 on 10 March 2000, then fell about 78% to 1,114 by October 2002. Companies with no profits were valued on page views and the belief that the internet had abolished valuation. Alan Greenspan's warning about irrational exuberance came in December 1996, more than three years and a tripling before the top, which shows that valuation is not a timing tool and that shorting a bubble early is ruinous. Momentum and trend following profited on the way up and, with trailing stops, avoided most of the collapse, while value investors were mocked in 1999 and vindicated after. Bubbles last longer than fundamentals suggest, a trailing exit matters more than calling the top, and the largest losses came from those who bought late and refused to sell on the way down."),
    ("The 2008 crisis and correlated risk", "The 2008 crisis grew from subprime mortgages packaged into securities rated as safe and held with high leverage by banks and funds. The S&P 500 fell about 57% from October 2007 to March 2009, Lehman Brothers failed on 15 September 2008, and assets that had looked diversified, including equities, commodities, credit, real estate and most hedge fund strategies, fell together as correlations approached one. What held up were government bonds, some currencies, and trend following: managed futures indices gained in the mid teens in percent for 2008. The August 2007 quant unwind had already shown how crowded, leveraged strategies liquidate together. Diversification across asset classes is not diversification across risk when the common factor is leverage and liquidity; tail hedges and trend following earn their carry cost in such years; and a strategy's worst case is the crisis, not its backtest."),
    ("The 2010 flash crash as a stop-loss lesson", "On 6 May 2010 the Dow Jones Industrial Average fell nearly 1,000 points, about 9%, within minutes and recovered most of the loss within roughly half an hour. The official report attributed the trigger to a single sell program of about 4.1 billion dollars in E-mini S&P futures executed by an algorithm keyed to volume, which overwhelmed liquidity as high frequency market makers withdrew. Some stocks traded at one cent and others at 100,000 dollars against stub quotes, and thousands of trades were cancelled. London trader Navinder Sarao was later charged with spoofing that added to the fragility. The lessons: liquidity is not constant, a stop-loss market order can fill at an absurd price in a liquidity vacuum, stop-limit orders and position sizing for gaps are the defenses, and the circuit breakers introduced afterwards reduce but do not remove the risk."),
    ("GameStop 2021 and short squeezes", "In January 2021 GameStop's short interest exceeded 100% of its float, and retail traders coordinating on Reddit bought shares and call options aggressively. The stock rose from around 17 dollars at the start of the month to an intraday high of 483 dollars on 28 January, driven by shorts forced to cover and by dealers hedging calls, a gamma squeeze. Melvin Capital lost about 53% in the month and needed a 2.75 billion dollar injection. Robinhood restricted buying, and the stock fell to around 40 dollars within weeks. A short position has unlimited loss and must be sized for that, crowded shorts are a liability regardless of fundamentals, most late buyers lost money, and being right about value does not matter if position sizing does not let the trader survive to be proven right."),
    ("The 2022 crypto collapse: Luna and FTX", "In May 2022 the Terra ecosystem collapsed: its algorithmic stablecoin UST, propped up by a lending protocol paying about 20% yield, lost its peg and the linked Luna token went from tens of dollars to near zero within a week, erasing roughly 40 billion dollars. Contagion took down Three Arrows Capital, Celsius and Voyager. In November 2022 the exchange FTX failed with a customer shortfall of about 8 billion dollars after lending client funds to its affiliated trading firm; its founder was convicted of fraud in 2023. Bitcoin fell about 77% from its November 2021 high near 69,000 dollars to around 15,500. The lessons are old ones: a yield with no visible source is paid from someone else's principal, counterparty and custody risk are real risk, leverage cascades through liquidations, and diversification within one asset class fails when the class collapses."),
    ("Archegos 2021 and hidden leverage", "Archegos Capital Management, Bill Hwang's family office, built concentrated positions in a handful of stocks including ViacomCBS, Discovery and several Chinese ADRs through total return swaps with multiple banks, so no single bank saw the whole exposure. Roughly 10 billion dollars of equity supported positions estimated at 50 billion or more. When ViacomCBS announced a share sale in March 2021 and its price fell, margin calls arrived from every bank at once, and forced liquidation of positions approaching 30 billion dollars on 26 March crushed the stocks. Banks lost about 10 billion dollars in total, including 5.5 billion at Credit Suisse and around 2.9 billion at Nomura, and Hwang was convicted of fraud in 2024. Leverage hidden from counterparties is still leverage, concentration in illiquid names makes the exit itself the risk, and a drawdown at that leverage is not survivable."),
    ("Market Wizards common denominators", "Jack Schwager's Market Wizards books, from 1989 through Hedge Fund Market Wizards in 2012 and Unknown Market Wizards in 2020, interview dozens of traders using wildly different methods, from discretionary macro to systematic trend following to options market making. The recurring themes Schwager draws out: risk management comes before entry method, each trader found an approach fitting their own personality rather than copying someone else, discipline in following the plan separates survivors from casualties, losing periods are normal and were expected, the best traders think independently and hold views loosely, and all treat trading as work requiring years of effort. No single indicator or setup is shared. Edge is personal and varied, but risk control, position sizing, discipline and patience are universal."),
    ("Mark Douglas and Trading in the Zone", "Mark Douglas's Trading in the Zone, published in 2000, argues that most traders fail not from lack of information but from beliefs that make it impossible to execute an edge consistently. His five fundamental truths, paraphrased: anything can happen; a trader does not need to know what happens next to make money; wins and losses are randomly distributed for any given edge; an edge is only a higher probability of one outcome over another; and every moment in the market is unique. From these follow his prescriptions: think in probabilities, define and accept the risk fully before entry so a loss carries no emotional charge, and execute a sample of at least 20 trades of one setup without deviation to experience the edge as a distribution. The book provides no edge; it addresses the psychology needed to trade one that has been independently verified."),
    ("Van Tharp's position sizing and R-multiples", "Van Tharp popularized the R-multiple: define the initial risk of a trade as 1R, the distance from entry to stop times position size, and express every result as a multiple of it, so a trade that risks 500 and makes 1,500 is a 3R winner. A system is then described by its distribution of R-multiples, with expectancy as the mean R per trade and the standard deviation of R as its variability. His System Quality Number, mean R divided by the standard deviation of R times the square root of the number of trades, resembles a t-statistic. His central claim, demonstrated with a marble game in which players trade the same random system with different sizing and end with wildly different equity, is that position sizing determines how much of a system's expectancy the trader keeps and whether they survive the drawdown to collect it."),
    ("Brett Steenbarger on performance psychology", "Brett Steenbarger, a psychiatrist who has coached traders at hedge funds and proprietary firms and writes the TraderFeed blog, reframes trading psychology as performance psychology. His central point across The Psychology of Trading, The Daily Trading Coach and Trading Psychology 2.0 is that most trading problems are not deep emotional disorders but performance problems: an inadequate edge, poor process, or a mismatch between trader and market. His methods come from sports and brief therapy: build on what the trader does well, use deliberate practice with rapid feedback, keep the review loop short, and attend to well-being and sleep because they set the baseline state. He also stresses that many traders should be researchers first, since no mindset work rescues a strategy with no expectancy. Psychology multiplies an edge; it does not replace one."),
    ("Why most trading education is sold to losers", "The economics of trading education are unfavorable to buyers. A trader with a durable edge scales capital, because that pays better than teaching; a seller of courses, signals or mentorship earns from fees, from broker affiliate commissions that rise with client turnover, and from prop-firm challenge fees, all of which grow with student numbers regardless of student results. The Brazilian day trading study was motivated partly by course providers advertising that day trading for a living was feasible, and found that about 97% of persistent day traders lost money. Prop-firm evaluations, assessed fairly, offer cheap leverage with capped downside to a trader who already has an edge, but the model depends on most applicants failing and paying again. Red flags are guaranteed returns, unaudited profit screenshots, and selling before any verifiable record; the best material costs little."),
]

SOURCES = {
    "feeds": [
        "https://traderfeed.blogspot.com/feeds/posts/default",
        "https://chatwithtraders.libsyn.com/rss",
        "https://bettersystemtrader.libsyn.com/rss",
        "https://www.toptradersunplugged.com/feed/",
        "https://alphaarchitect.com/feed/",
        "https://www.trendfollowing.com/feed/",
    ],
    "subreddits": ["Daytrading", "Trading", "FuturesTrading", "algotrading", "wallstreetbets"],
    "github_queries": ["topic:trading-journal", "topic:trading-psychology", "trade journal R-multiple expectancy", "topic:behavioral-finance"],
    "arxiv_topics": [
        "retail investor trading performance",
        "disposition effect individual investors",
        "overconfidence trading volume behavioral finance",
        "attention induced trading retail",
        "day trading profitability evidence",
    ],
    "urls": [
        "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=219228",
        "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=94142",
        "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3423101",
        "https://www.esma.europa.eu/press-news/esma-news/esma-agrees-prohibit-binary-options-and-restrict-cfds-protect-retail-investors",
        "https://en.wikipedia.org/wiki/Long-Term_Capital_Management",
        "https://en.wikipedia.org/wiki/2010_flash_crash",
        "https://en.wikipedia.org/wiki/Archegos_Capital_Management",
        "https://en.wikipedia.org/wiki/Turtle_trading",
    ],
}
