"""Risk and money management: sizing, limits, stops, drawdown control and the math behind survival.

Goes deeper than the curriculum's position sizing, Kelly, stop loss, drawdown,
leverage and hedging cells, under different titles, so the brain can link
each practical rule back to those foundations.
"""

from __future__ import annotations

DOMAIN = "Risk and money management"

LESSONS: list[tuple[str, str]] = [
    ("Fixed fractional versus fixed ratio sizing", "Fixed fractional sizing risks a constant fraction f of current equity on every trade: position = f * equity / stop distance, with f typically 0.5-2%. Size grows and shrinks with the account, so compounding is automatic and percentage drawdown is bounded by the sequence of losses. Ryan Jones's fixed ratio method instead adds one contract each time equity grows by a fixed delta per contract, usually set near the largest expected drawdown per contract, so early growth is aggressive and later growth conservative. Fixed ratio suits small futures accounts where one contract is already a large share of equity, but it has no theoretical optimality and its risk per trade drifts as the account changes. Fixed fractional links directly to the Kelly criterion, volatility targeting and expectancy, which is why systematic traders prefer it."),
    ("Volatility targeting in practice", "Volatility targeting sets notional so a position's expected annualized volatility equals a target: notional = target_vol * equity / instrument_vol, with instrument_vol an exponentially weighted standard deviation of daily returns with a 20-60 day half-life, annualized by the square root of 252. Typical targets are 10-20% for a diversified portfolio and 2-5% per instrument. Because volatility clusters, recent volatility forecasts near-term volatility well; Moreira and Muir and Harvey et al. show the rule raises Sharpe ratio and cuts drawdown for equity, momentum and futures strategies. It fails when volatility jumps faster than the lookback adapts, at the start of crashes, so a leverage cap and a floor on the volatility estimate are needed. Shorter lookbacks track regimes faster but churn positions and raise transaction costs."),
    ("Risk of ruin", "Risk of ruin is the probability that equity falls to a level at which trading stops, either zero or a drawdown threshold. For even-money bets with win probability p above 0.5, risking one unit per trade from a stake of n units, gambler's ruin gives ruin = ((1-p)/p)^n. For trades with a payoff ratio, a common approximation uses the mean and variance of R-multiples: ruin is about exp(-2 * mean * stake / variance), with the stake in units of risk per trade. Ruin falls exponentially with the number of risk units, which is why risking 1% (100 units) versus 10% (10 units) separates negligible from near-certain ruin for a modest edge. The formulas assume a stable edge and independent trades; regime change and correlated losses make real ruin likelier, so position sizing should stay well below the calculated safe fraction."),
    ("R-multiples and expectancy tracking", "An R-multiple expresses a trade's result as a multiple of its initial risk: a trade risking 1% that gains 2.5% is +2.5R and a full stop-out is -1R. Tracking R normalizes across instruments and account sizes and makes expectancy simply the average R per trade, with the standard deviation of R describing dispersion. Van Tharp popularized the framework and the System Quality Number, expectancy over standard deviation of R times the square root of trade count, a t-statistic in disguise. A journal records planned risk, realized R, holding time and exit reason; the distribution of R shows whether the edge comes from a few large winners. Slippage and gaps make realized losses worse than -1R, so track the worst loss, and remember expectancy needs hundreds of trades before it is distinguishable from zero."),
    ("Optimal f and why traders avoid it", "Ralph Vince's optimal f is the fraction of equity, expressed relative to the largest historical loss, that maximizes the terminal wealth relative of a trade sequence: TWR(f) is the product over trades of (1 + f * (-trade / largest loss)), maximized numerically. It generalizes the Kelly criterion to arbitrary trade distributions and typically yields 20-50% of equity per trade. Traders avoid it because the expected drawdown at optimal f is enormous, often 80% or more; because it depends on the largest loss in the sample, which the future will exceed; and because the growth curve is flat near the optimum while the drawdown curve is not, so overestimating f costs little growth and much pain. Optimal f is useful as an upper bound showing how far real position sizing, usually a tenth of it, sits from ruin."),
    ("Fractional Kelly under estimation error", "The Kelly fraction for a continuous return stream is f = mu / sigma^2, excess return over variance; a Sharpe ratio of 0.5 at 15% volatility gives 0.075 / 0.0225, or 3.3 times leverage, which nobody should run. Estimation error is the reason. The standard error of a mean return over T years is sigma / sqrt(T), so ten years of data give a Kelly estimate whose confidence interval spans zero to twice the point estimate; betting full Kelly overbets half the time, and betting beyond twice Kelly has negative expected growth. Baker and McHale show that shrinking toward zero in proportion to the uncertainty is the Bayesian answer, landing at a quarter to a half of Kelly. Half Kelly keeps about 75% of the growth rate with half the volatility, and drawdown at full Kelly regularly exceeds 50%."),
    ("Drawdown control rules and equity curve trading", "Drawdown control rules cut position size as losses accumulate: a common schedule halves size after a 10% drawdown, quarters it after 15% and stops trading at 20% pending review, restoring size as equity recovers. Equity curve trading applies a moving average or breakout rule to the strategy's own equity curve, trading full size when equity is above its 50 or 100 trade moving average and reduced or zero size below it. Backtests of equity curve filters are mixed: they help strategies with persistent regimes, such as trend following in choppy markets, and hurt mean reversion strategies whose losses cluster right before recoveries, because the filter switches off before the rebound. The reliable part is the cut in the worst drawdowns; the cost is lower long-run return. Rules must be set before the drawdown, not during it."),
    ("Value at Risk and its limits", "Value at Risk answers one question: over horizon h at confidence c, what loss will not be exceeded? A one-day 99% VaR of 2% of equity means losses beyond 2% are expected about once every 100 days. Parametric VaR assumes normal returns, VaR = z * sigma * sqrt(h) with z = 2.33 at 99%; historical VaR takes the empirical quantile of the last 250-500 days; Monte Carlo VaR simulates from a fitted model. VaR is easy to aggregate and explain, which is why regulators and prime brokers use it. Its limits are severe: it ignores the size of losses beyond the threshold, it is not subadditive so a portfolio can show more VaR than its parts, it understates fat tails, and a lookback that missed the last crisis gives a low VaR right before the next one. Use VaR for monitoring, never as the position sizing limit."),
    ("Expected shortfall and conditional VaR", "Expected shortfall, also called conditional VaR, is the average loss in the worst (1-c) fraction of outcomes: ES at 97.5% is the mean of the 2.5% worst days. For normal returns ES at 97.5% is about 2.34 sigma, close to 99% VaR, which is why Basel replaced 99% VaR with 97.5% ES. Unlike VaR it is coherent, meaning subadditive, so diversification never increases it, and it responds to the size of tail losses rather than only their frequency. Historical ES averages the worst 2.5% of returns over a 250-1000 day window, which for one year means six or seven observations, so the estimate is noisy and dominated by whichever crisis is in the window. Traders use it to set stress limits and to compare strategies with fat tails, such as short volatility, where Sharpe ratio and VaR both flatter."),
    ("Stress testing and scenario analysis", "Stress testing asks what the portfolio would lose under specific extreme scenarios rather than under a statistical distribution. Historical scenarios replay actual moves such as October 1987, the 2008 crisis, March 2020 or the 2022 rate shock, applying those returns and correlation changes to current positions. Hypothetical scenarios shock risk factors directly: equities down 20%, volatility doubling, credit spreads 300 basis points wider, all at once. Reverse stress testing works backward from a loss that would end the fund to find the scenario that produces it. Good practice runs stresses weekly, limits the worst scenario loss to perhaps 25% of equity, and includes liquidity assumptions, since the hedge that saves the portfolio on paper may not be executable. Stress tests fail through lack of imagination: the next crisis rarely repeats the last one, and scenario correlations are assumptions."),
    ("Correlation risk and portfolio heat", "Portfolio heat is the total open risk across all positions, the loss if every stop loss is hit at once, typically capped at 5-10% of equity for a discretionary trader and expressed as a volatility number for a systematic one. Correlation risk is the recognition that ten positions each risking 1% are not ten independent bets when all are long technology stocks or all short the dollar; their combined risk is closer to one position risking 10%. Portfolio volatility combines position volatilities through the correlation matrix, and n positions with average pairwise correlation rho behave like n / (1 + (n-1) * rho) independent positions. Correlations rise sharply in selloffs, so heat measured with calm-period correlations understates crisis heat; stress the matrix toward 0.8 or 1.0 before setting limits. Trend followers cap heat by sector as well as in total."),
    ("Concurrent positions and sector exposure limits", "Limits on the number of concurrent positions and on exposure per sector are crude but effective correlation controls. The Turtle rules allowed at most 4 units in a single market, 6 in closely correlated markets, 10 in loosely correlated ones and 12 in one direction, with a unit sized at 1% of equity per ATR of stop distance. Equity portfolios commonly cap a single name at 5-10% of capital, a sector at 20-30%, and net exposure within a band such as plus or minus 30% for a market-neutral book. Limits enforce diversification when the signal generator concentrates, which happens exactly when a theme is working and about to reverse. They fail when sector labels miss the real common factor, such as rate sensitivity across utilities, REITs and growth stocks in 2022; factor exposure reports catch what sector counts miss."),
    ("Pyramiding and scaling in and out", "Pyramiding adds to a winning position as it moves in the trader's favor, usually in decreasing size (a 4-3-2-1 pattern) so the average entry does not chase price; the Turtles added a unit every half ATR of favorable move up to a cap. The danger is that the position is largest exactly when the trend is most extended, so total open risk must be recomputed after each add and the stop loss on the whole position tightened. Scaling in splits a planned entry into tranches to reduce timing risk; scaling out takes partial profits at targets and lets the remainder run. Backtests generally show scaling out lowers both return and drawdown, because it sells the winners trend following depends on. Neither is a source of edge; both reshape the return distribution, which is a preference about drawdown."),
    ("Trailing stop methods compared", "A trailing stop follows price to lock in profit. Common variants: a fixed percentage below the highest close, an ATR multiple (2-3 ATR for swing trades, 4-6 for longer trend following), a Chandelier exit at the highest high minus 3 ATR, a moving average such as the 20 or 50 day, the parabolic SAR, and a Donchian channel exit at the lowest low of the last 10-20 days. Tight trails cut the average winner and raise the win rate; wide trails hold through noise and capture long trends with a lower win rate and more give-back at the end. Tests on futures trend following usually find ATR and channel trails beat fixed percentage ones because they adapt to volatility. No trailing stop protects against gaps, and every trail surrenders part of the peak profit, the price of never capping the winner."),
    ("Time stops", "A time stop exits a trade that has not worked within a set number of bars, regardless of price. A thesis usually has a horizon: a mean reversion entry expects a snap-back within days, a breakout expects follow-through within a week, and a position going nowhere ties up capital and open risk while saying nothing about whether the thesis is intact. Typical values are 3-5 days for short-term mean reversion, 10-20 days for swing trades and one to three months for earnings-driven trades. Time stops raise trade count and cut holding time, improving capital turnover and reducing gap risk and overnight risk. Evidence from statistical arbitrage and short-term reversal strategies shows time exits capture most of the profit because reversal returns concentrate in the first few days. Time stops hurt trend following, whose profits come from the trades held longest."),
    ("Stop placement across volatility regimes", "A stop loss set as a fixed percentage ignores that a 2% move is noise in a stock with 60% annualized volatility and a large move in one with 15%. Placing the stop as a multiple of ATR or recent standard deviation, and sizing the position from the stop distance, keeps the probability of a noise stop-out roughly constant across regimes: when volatility doubles the stop widens and size halves, so dollar risk is unchanged. The trap is that volatility rises fastest at the start of a selloff, when a stop set on calm-period ATR is too tight and gets whipsawed; recomputing stops daily on 14-20 day ATR adapts within a week or two. Some traders widen the multiple in high volatility (3 ATR instead of 2); others refuse new entries when ATR exceeds twice its 100 day average."),
    ("Gap risk and overnight risk", "A stop loss executes only when the market trades, so an overnight gap through the stop delivers a loss larger than planned; single stocks routinely gap 10-30% on earnings, and in January 2015 the Swiss franc moved 20% in minutes when its peg broke. The true worst case is the gap size times the position, not the stop distance, so position sizing must assume a plausible gap, for individual equities often 3-5 times the daily ATR. Overnight risk is the broader point that most large equity moves occur between the close and the open, when the trader cannot act. Remedies include smaller size overnight, closing before scheduled events, hedging with index futures or options over the event window, and preferring instruments that trade nearly continuously. Day traders remove gap risk at the cost of the overnight return, which carries most of the equity premium."),
    ("Liquidity risk and size versus daily volume", "Liquidity risk is the cost of getting out. A position that is a large fraction of average daily volume cannot be exited without moving the price, and in a crisis volume vanishes exactly when exit is required. Rules of thumb cap a position at 1-5% of ADV for a strategy that must exit within a day and 10-20% for one that can work out over a week; the square-root impact law says cost scales with the square root of participation rate, so doubling size raises impact by about 41%. Estimate exit cost as spread plus impact and size positions so that a forced liquidation in half the normal volume still costs less than the planned stop loss. Small caps, crypto altcoins and long-dated options all look liquid until stressed; LTCM and the August 2007 quant unwind show crowded illiquid positions turn correlation risk into liquidity risk."),
    ("Margin math for futures and forex", "Futures margin is a performance bond, not a loan: an E-mini S&P contract controls 50 times the index level in notional and requires initial margin near 5-10% of that, so a position at full margin is 10-20 times leveraged. Forex brokers quote leverage as 30:1 or 50:1, meaning a 2-3% margin requirement; a 2% adverse move on a 50:1 position wipes out the margin. The leverage that matters for risk is notional divided by equity, and the right way to set it is volatility targeting: with a 15% target and an instrument with 20% volatility the notional is 0.75 times equity, far below what the broker permits. Keep excess margin at least equal to the worst plausible multi-day loss, typically 3-5 times the daily volatility of the notional, because maintenance margin calls force liquidation at the worst time and exchanges raise margins in volatile periods."),
    ("The asymmetry of losses", "Losses and gains are not symmetric because returns compound: a 10% loss needs 11.1% to recover, 25% needs 33%, 50% needs 100% and 90% needs 900%, following recovery = loss / (1 - loss). This is the same math as volatility drag: geometric growth is approximately the arithmetic mean minus half the variance, so a strategy with a 10% average return and 40% volatility compounds near 2%, and at 45% volatility it stops compounding at all. Leverage raises the arithmetic mean linearly and the drag quadratically, which is why there is an optimal leverage, the Kelly fraction, beyond which more leverage lowers long-run growth even with a positive edge. Reducing variance at a small cost in mean return therefore often raises compounded wealth. Drawdown depth, not average return, determines how fast an account compounds."),
    ("Daily loss limits and circuit breakers", "A daily loss limit halts trading for the rest of the day once losses reach a threshold, usually 2-3 times the planned risk per trade or 1-3% of equity for an active day trader; proprietary trading firms enforce these mechanically and lock the platform. The rationale is behavioral and statistical: losing days cluster, judgment degrades after losses, and the largest single-day losses in most trading journals come from revenge trading after the first two or three losses. Weekly and monthly circuit breakers extend the logic, for example stop for the week at 5% and for the month at 8%, with a mandatory review before resuming. The cost is that some strong recovery days are missed, which backtests show is small relative to the tail losses avoided. A circuit breaker only works if software or another person enforces it."),
    ("Risk per trade, per day and per strategy", "Risk should be budgeted at several nested levels. Risk per trade is stop distance times size, typically 0.25-1% of equity for systematic traders and 1-2% for discretionary ones. Risk per day is the sum of what could be lost across trades opened that day plus open positions, often capped at 3-5% of equity. Risk per strategy is a volatility or drawdown budget for each system in a portfolio, such as an 8% annualized volatility allocation, so one strategy in a bad regime cannot dominate the book. Portfolio risk is the aggregate after correlation. Limiting only one level fails: a 1% per-trade limit with no daily cap permits twenty correlated 1% losses, and a portfolio volatility target with no per-trade limit lets one position carry the whole budget. The per-trade limit should bind most days and the higher levels only in stress."),
    ("Portfolio-level stop", "A portfolio-level stop flattens or sharply reduces the entire book when total drawdown or loss over a window crosses a threshold, for example cutting gross exposure by half at a 10% drawdown from peak and to zero at 15%, with re-entry only after a cooling period or a fresh signal. It is the last defense against every position losing at once because they share a factor that was invisible until the crisis. Funds implement it as a drawdown-triggered deleveraging schedule; prop firms as a hard account-level stop. The cost is path dependence: a portfolio that stops out near the bottom locks in the loss and misses the recovery, as many quant funds did in August 2007 and March 2020. Set the stop far enough that normal drawdowns, roughly twice the backtested maximum, do not trigger it, and close enough to make survival certain."),
    ("Hedging costs versus benefits", "Every hedge is a trade with negative expected return that buys a reduction in variance or tail loss, and the decision is whether that reduction is worth the drag. Hedging a stock portfolio with index futures costs almost nothing in carry but removes the equity premium along with the risk; hedging with puts costs the volatility risk premium, historically 1-3% of notional per year for continuous at-the-money protection and far more when volatility is high; hedging a currency exposure costs the interest differential. The benefit is measured by the improvement in compounded growth rate and maximum drawdown, not by whether the hedge made money. Hedge ratios come from regression beta or option delta and drift as correlations change, so they need rebalancing. Over-hedging turns a portfolio net short, and basis risk appears when hedge and exposure diverge."),
    ("Tail hedging with options", "Tail hedging buys far out-of-the-money puts, usually 20-30% below the market with two to three months to expiry, rolled monthly, spending a fixed budget of 0.5-1.5% of the portfolio per year. In a crash the puts can return 10-30 times their cost, as in March 2020, offsetting much of the portfolio loss and providing cash to rebuy at the bottom. The cost is steady bleed in calm years, and the evidence is mixed: over long samples continuous put buying has lowered compounded returns for most investors, while trend following and volatility targeting have provided cheaper crash protection. Tail hedges work best when sized against a specific liability, when the implied volatility skew is cheap, and when they let the rest of the portfolio run more leverage. Monetizing the puts during the crash matters more than strike selection."),
    ("Risk budgeting across strategies", "Risk budgeting allocates a portfolio's total risk, usually an annualized volatility target or an expected shortfall limit, across strategies in proportion to their expected contribution and diversification rather than by capital. Each strategy's marginal risk contribution is its weight times the covariance of its returns with the portfolio, divided by portfolio volatility, and the budget is set so those contributions sum to the target. A common scheme gives equal risk contribution to every strategy, then tilts toward those with higher expected Sharpe ratio or lower correlation to the rest of the book, reviewing quarterly and scaling back strategies that breach. The covariance estimate is unstable across regimes, so budgets are computed with correlations stressed upward and given wide bands to avoid churn. It removes the error of funding the strategy with the best recent returns, usually the one about to underperform."),
    ("Risk parity in practice", "Risk parity weights assets so each contributes equal risk: with volatility alone, weight is inversely proportional to volatility, so a 60/40 stock-bond mix becomes roughly 25/75 by capital and 50/50 by risk; with a full covariance matrix the weights solve numerically for equal marginal contributions. Because bonds have low volatility the unlevered portfolio has low return, so practitioners lever it to a 10-12% volatility target, which adds financing cost and leverage risk. Volatility estimates use 20-120 day windows and portfolios rebalance monthly or on drift bands. Live results since the 1990s show a higher Sharpe ratio than 60/40 with similar drawdowns in equity crises, but 2022 exposed the weakness: when stocks and bonds fall together, a levered portfolio of both loses on both legs and deleverages into the decline. It needs a leverage cap, a correlation stress test and a plan for rising rates."),
    ("Rebalancing frequency and drift", "Rebalancing returns portfolio weights to target after prices move them. Calendar rebalancing at monthly or quarterly intervals is simplest; threshold rebalancing acts when a weight drifts beyond a band, typically 5 percentage points absolute or 20-25% relative, and captures more of the rebalancing premium while trading less. That premium comes from selling assets that have risen and buying those that have fallen, and is largest between volatile, low-correlation assets. Letting weights drift is a momentum bet and rebalancing is a mean reversion bet, so rebalancing too often in trending markets sells the winner repeatedly, and 2008 showed that rebalancing into a falling asset can deepen drawdown. For volatility targeted strategies the drift that matters is in risk, not capital; daily volatility updates with a 10-20% no-trade band around target size keep transaction costs down."),
    ("Correlated strategies in crises", "Strategies that look independent in calm markets often share a hidden exposure that appears only in crises: liquidity provision, short volatility, carry, and mean reversion in equities and credit are all effectively short a crash. In August 2007 statistical arbitrage books with near-zero historical correlation lost together within days because they held the same crowded positions; in March 2020 risk parity, volatility targeting and trend following all cut exposure at once, amplifying the selloff. Correlation matrices estimated over calm years understate crisis co-movement, so the diversification benefit computed from them is partly fictional. Defenses include stressing all correlations toward one for sizing, classifying strategies by what they are short (liquidity, volatility, credit) rather than by asset class, allocating part of the risk budget to long-convexity strategies such as trend following, and keeping gross leverage low enough that a simultaneous drawdown everywhere is survivable."),
    ("Counterparty and exchange risk", "Counterparty risk is the chance that the venue, broker or clearing house holding your assets fails or refuses to pay. In crypto it is the dominant risk: Mt. Gox in 2014 and FTX in 2022 each cost customers billions, and exchange hacks and withdrawal freezes occur every year. Practical rules are to hold on any exchange only what open positions and margin require, keep the rest in self-custody, spread activity across venues, and treat exposure to any single venue as a position with a limit, for example 10-20% of capital. Regulated brokers carry less risk through segregation and insurance schemes such as SIPC or FSCS, but MF Global in 2011 showed segregated funds can still be lost. Futures cleared through a central counterparty carry the least risk. Counterparty risk cannot be diversified away by trading well; it is a due diligence and allocation decision."),
    ("Model risk", "Model risk is loss from a model being wrong, misestimated or misused: incorrect assumptions such as normal returns or stable correlations, parameters fit to a regime that ended, coding errors, and use outside the domain the model was validated for. Long-Term Capital Management's models were right about convergence and wrong about the path and the liquidity needed to survive it; the 2007 quant unwind and the 2020 volatility spike were similar. Controls adopted from banks are independent validation, benchmarking against a simpler model, sensitivity analysis on every input, walk-forward and out-of-sample testing, and a model inventory with owners and review dates. For a trader the practical rules are to size a new model at a fraction of its backtested capacity until live results accumulate, to cap leverage so a completely wrong model is survivable, and to define in advance the live drawdown that retires it."),
    ("Operational risk", "Operational risk is loss from failed processes, people and systems rather than from market moves. Fat-finger errors, such as a 2014 Japanese order for 617 billion dollars of stock, wrong-sign trades, duplicate submissions and unit confusion (shares versus contracts, lots versus units in forex) are the common cases; connectivity failures in a fast market and runaway algorithms are the expensive ones, as Knight Capital's 440 million dollar loss in 45 minutes in 2012 showed. Controls are cheap relative to the losses: hard maximum order size and notional limits at the broker and in code, price collars that reject orders far from the last trade, a kill switch reachable by phone, a backup connection, daily position reconciliation, and a deployment checklist for new code. Automated systems should fail closed, flattening or halting rather than trading blind. Operational losses are pure subtraction from expectancy."),
    ("Sizing mean reversion versus trend following", "Mean reversion and trend following have opposite return distributions and need different position sizing. Mean reversion wins often and small and loses rarely and large; its worst trades are those where the stretched price keeps going, so the stop loss defines the tail and sizing should assume the stop is hit through a gap. Because entries fade the move, adding to losers is tempting and is the classic way mean reversion accounts blow up, so a hard cap on scale-ins and on total risk per idea is essential. Trend following loses often and small and wins rarely and large; positions are sized on volatility at entry, usually 0.5-1% of equity per ATR of stop distance, then trailed as profits grow. Trend following can hold more concurrent positions because losses are capped by design; mean reversion should hold fewer and smaller ones."),
    ("Sizing around scheduled events", "Scheduled events such as earnings, FOMC decisions, CPI and payrolls produce known volatility spikes that daily volatility estimates do not anticipate. The implied move from options, roughly the at-the-money straddle price divided by the stock price, gives the market's estimate of the event gap, commonly 5-10% for large-cap earnings and far more for small caps. Rules used in practice are to cut single-stock positions to a quarter or a half through earnings, or close them unless the strategy is explicitly an earnings strategy; to widen or remove stops through the event, since a stop loss cannot execute inside a gap; and to avoid new index or forex entries in the 30 minutes around macro releases, when spreads widen and slippage is severe. Systematic traders either add an event calendar to the risk model or accept events as part of the backtested distribution."),
    ("Monte Carlo simulation of trade sequences", "Monte Carlo simulation resamples a strategy's historical trade results, in R-multiples or percentage returns, to generate thousands of alternative equity curves and thereby the distribution of drawdown, time to recovery and terminal wealth rather than the single path history produced. The simplest form draws trades with replacement; a block bootstrap preserves the clustering of wins and losses; parametric versions draw from a fitted distribution with fatter tails than the sample. The outputs used for position sizing are the 95th or 99th percentile of maximum drawdown for a given risk per trade and the probability of hitting a ruin threshold; a common rule is to choose the risk fraction at which the 95th percentile drawdown equals what the trader can tolerate. Monte Carlo cannot invent a loss larger than any in the sample, so add a synthetic worst trade, and it assumes the edge persists."),
    ("Drawdown duration versus depth", "Drawdown has two dimensions: depth, the percentage decline from peak, and duration, the time from the peak until a new high. Traders fixate on depth, but duration is what causes strategies to be abandoned and funds redeemed: a 12% drawdown lasting three years is harder to survive than a 25% drawdown recovered in six months. For a strategy with Sharpe ratio S the expected length of the longest drawdown scales roughly with 1 / S^2 in years, so a Sharpe 0.5 strategy routinely spends two to four years under water and a Sharpe 1 strategy about a year. Trend following shows the longest durations because its returns come in bursts. Report maximum drawdown duration and time under water in every backtest, and decide the tolerance for duration before trading. A drawdown longer than the backtest's longest is weaker evidence of failure than a deeper one."),
    ("Recovery math after a loss", "After a loss L the return needed to recover is L / (1 - L), and with fixed fractional sizing recovery happens in percentage terms, so the number of trades needed depends on expectancy. A strategy earning 0.3R per trade while risking 1% of equity gains about 0.3% per trade, so a 20% drawdown, which needs a 25% recovery, takes about 75 trades on average, with wide dispersion. Cutting risk after a drawdown lengthens recovery, which is the deliberate trade-off of drawdown control rules: they cap depth at the cost of duration. Raising risk to recover faster, sometimes called martingale sizing, shortens expected recovery only if the edge is intact and raises ruin probability sharply if it is not, which is the most common way a drawdown becomes a blow-up. Check whether the edge has decayed, against the backtested distribution of drawdowns, before changing size."),
    ("The 2% rule assessed", "The 2% rule says never risk more than 2% of equity on a single trade, measured as the distance to the stop loss times position size. Its virtue is that ruin from a losing streak becomes nearly impossible: ten consecutive losses cost about 18%, twenty cost 33%, and a trader with a 40% win rate sees ten in a row about once every 1,700 trades. Its weaknesses are that it ignores correlation between simultaneous positions, so ten 2% positions in one sector are a 20% bet; that for a strategy with a small edge 2% is often above the half-Kelly fraction, so it is aggressive rather than conservative; and that it ignores gap risk. Professional systematic traders typically run 0.25-1% per position and control risk through portfolio volatility. The rule is a reasonable ceiling for beginners and a poor substitute for portfolio-level risk budgeting."),
]

SOURCES = {
    "feeds": [
        "https://blog.quantinsti.com/rss",
        "https://quantpedia.com/feed",
        "https://financial-hacker.com/feed/",
        "https://www.quantstart.com/feed/",
        "https://robotwealth.com/feed/",
        "https://www.risk.net/feeds/rss/category/risk-management",
        "https://alphaarchitect.com/feed/",
        "https://mrzepczynski.blogspot.com/feeds/posts/default",
    ],
    "subreddits": ["algotrading", "quant", "Daytrading", "swingtrading", "Forex"],
    "github_queries": [
        "topic:risk-management trading",
        "position sizing kelly criterion python",
        "value at risk expected shortfall python",
        "monte carlo drawdown trading simulation",
        "topic:portfolio-optimization risk parity",
    ],
    "arxiv_topics": [
        "risk of ruin position sizing",
        "drawdown control trading strategies",
        "expected shortfall estimation backtesting",
        "volatility targeting portfolio",
        "fractional Kelly estimation error",
    ],
    "urls": [
        "https://en.wikipedia.org/wiki/Kelly_criterion",
        "https://en.wikipedia.org/wiki/Risk_of_ruin",
        "https://en.wikipedia.org/wiki/Value_at_risk",
        "https://en.wikipedia.org/wiki/Expected_shortfall",
        "https://en.wikipedia.org/wiki/Risk_parity",
        "https://en.wikipedia.org/wiki/Gambler%27s_ruin",
        "https://www.quantstart.com/articles/Money-Management-via-the-Kelly-Criterion/",
        "https://www.bis.org/bcbs/publ/d457.htm",
    ],
}
