"""The seed curriculum: foundational trading knowledge the brain is born with.

Everything else the brain learns (papers, data, backtests) links back to these
cells, so a question about "risk" reaches drawdown, position sizing, Kelly and
the backtests that measured them. Add to CURRICULUM freely: every entry is
(title, text), and ``seed()`` is idempotent.
"""

from __future__ import annotations

from bigbrain.brain import Brain

CURRICULUM: list[tuple[str, str]] = [
    ("Trend following", "Trend following bets that prices that have been rising keep rising and prices that have been falling keep falling. Systems use moving average crossovers, breakouts of recent highs, or channel breaks to enter, and trailing stops to exit. It has a low win rate (often 30-40%) but a high payoff ratio, because losses are cut fast and winners are held. It suffers in sideways, choppy markets and shines in persistent trends and crises. Diversifying across many uncorrelated markets is what makes trend following robust."),
    ("Momentum", "Momentum is the tendency of assets that outperformed over the past 3-12 months to keep outperforming over the next month or so, skipping the most recent month to avoid short-term reversal. It is one of the most robust anomalies across equities, futures, forex and crypto. Explanations include under-reaction to news and herding. Momentum crashes happen after sharp bear market rebounds, so volatility scaling and drawdown controls matter."),
    ("Mean reversion", "Mean reversion assumes that stretched prices snap back toward an average: an oversold RSI, a close below the lower Bollinger band, or a spread between two cointegrated assets that drifts too wide. Short horizon (days) mean reversion works well in liquid equities and pairs trading. The main risk is that a 'stretched' move is actually the start of a new trend, so stop losses and position sizing are essential. Mean reversion and momentum coexist at different horizons."),
    ("Support and resistance", "Support is a price area where buying has repeatedly stopped declines; resistance is where selling has capped rallies. They come from prior swing highs and lows, round numbers, moving averages and volume clusters. A breakout through resistance on high volume often turns that level into support. Traders place stop losses just beyond these levels, which also makes them targets for stop hunts."),
    ("Breakout trading", "Breakout trading enters when price leaves a consolidation range, expecting volatility expansion. Classic rules: buy a new 20-day or 55-day high (Donchian channel, used by the Turtle traders), or a close above the upper Bollinger band. False breakouts are common, so traders demand volume confirmation and use ATR-based stops. Breakouts are a form of trend following."),
    ("Moving averages", "A simple moving average (SMA) is the mean of the last N closes; an exponential moving average (EMA) weights recent prices more. They smooth noise and define trend: price above a rising 200-day SMA is a bull regime. Crossovers such as the golden cross (50-day above 200-day) and death cross generate trend following signals with lag. Moving averages whipsaw in ranges and are best combined with a volatility filter."),
    ("RSI (Relative Strength Index)", "RSI compares average gains to average losses over a period, usually 14, and maps the result to 0-100. Readings above 70 are called overbought and below 30 oversold. In a strong trend RSI can stay overbought for weeks, so overbought is not a sell signal by itself. Divergence between RSI and price, and RSI mean reversion (buy below 30, exit above 50-55), are the two most common uses. RSI is a momentum oscillator."),
    ("MACD", "MACD subtracts the 26-period EMA from the 12-period EMA to form the MACD line, then smooths that with a 9-period EMA signal line; the histogram is their difference. A MACD line crossing above its signal line is a bullish momentum signal; crossing below is bearish. Zero-line crosses indicate trend changes. MACD lags and generates whipsaws in sideways markets."),
    ("Bollinger bands", "Bollinger bands plot a 20-period SMA with bands two standard deviations above and below. Band width measures volatility: a squeeze (narrow bands) often precedes a breakout, and price touching a band shows a stretched move. Mean reversion traders fade band touches in ranges; breakout traders buy closes outside the band in trends. Which one works depends on the market regime."),
    ("ATR and volatility-based stops", "Average True Range (ATR) measures the typical bar range including gaps. Traders size stops as a multiple of ATR (for example 2x ATR) so that stops adapt to volatility instead of being placed at arbitrary percentages. ATR also drives volatility-based position sizing: risk a fixed fraction of equity per trade, divided by the ATR stop distance, gives position size."),
    ("Volume and VWAP", "Volume confirms price moves: a breakout on heavy volume is more reliable than one on light volume. VWAP (volume-weighted average price) is the average price paid during the day, used by institutions as an execution benchmark and by intraday traders as dynamic support and resistance. Volume spikes at turning points can signal capitulation or climax."),
    ("Candlestick patterns", "Candlestick patterns like doji, hammer, shooting star and engulfing bars describe the battle between buyers and sellers within a bar. Individually they have weak statistical edge; their value comes from context: a hammer at a support level after a decline with rising volume. Backtests generally show candlestick patterns need confirmation from trend and volatility."),
    ("Chart patterns", "Chart patterns such as head and shoulders, double tops and bottoms, triangles and flags describe consolidation shapes that precede continuation or reversal. They are subjective and prone to hindsight bias. When tested systematically the edge is small, but patterns remain useful as a framework for where stop losses and breakout entries sit."),
    ("Market regimes", "Markets alternate between trending and mean reverting, and between low and high volatility regimes. Trend following earns in trending regimes and bleeds in ranges; mean reversion is the mirror image. Regime detection uses realized volatility, moving average slope, the VIX, or hidden Markov models. Strategies that adapt exposure to regime have far better drawdowns than static ones."),
    ("Volatility", "Volatility is the dispersion of returns, quoted annualized: 16% volatility means a typical daily move of about 1%. Realized volatility is measured from past returns; implied volatility is inferred from option prices (the VIX for the S&P 500). Volatility clusters: high-vol days follow high-vol days. Volatility targeting, scaling position size inversely with volatility, is one of the most reliable improvements to any strategy's Sharpe ratio."),
    ("Position sizing", "Position sizing decides how much to risk per trade and matters more than entry timing. Fixed fractional sizing risks 1-2% of equity per trade. Volatility targeting sizes positions so each contributes equal risk. The Kelly criterion gives the growth-optimal fraction f = edge / odds; full Kelly is too volatile in practice, so traders use half or quarter Kelly. Oversizing turns a positive expectancy strategy into ruin."),
    ("Kelly criterion", "The Kelly criterion maximizes long-run geometric growth: for a bet with win probability p and payoff ratio b, the optimal fraction is f = (p*b - (1-p)) / b. Betting more than Kelly lowers growth and raises ruin risk; half Kelly gives about 75% of the growth with far less drawdown. Kelly assumes you know p and b exactly, which traders never do, so fractional Kelly hedges estimation error."),
    ("Stop losses", "A stop loss is a predefined exit that caps the loss on a trade. Stops should be placed where the trade thesis is wrong (beyond support, beyond an ATR multiple), not at a round dollar amount. Trailing stops lock in profit in trends. Stops guarantee small losses but also guarantee being taken out by noise, so stop distance and position size must be set together: tighter stops mean larger size for the same risk."),
    ("Expected value and expectancy", "A strategy's expectancy is win rate times average win minus loss rate times average loss. A 35% win rate is fine with a 3:1 payoff ratio; a 70% win rate loses money if losers are five times the winners. Traders should evaluate edge per trade in units of risk (R multiples), and remember that expectancy is only meaningful with enough trades to be statistically significant."),
    ("Drawdown", "Drawdown is the decline from an equity peak to the subsequent trough. Maximum drawdown is the worst such decline in the history. It is the risk measure traders feel most: a 50% drawdown needs a 100% gain to recover. Drawdown control rules, such as halving size after a 10% drawdown, reduce the tail. Backtested max drawdown understates future drawdown; expect roughly double."),
    ("Sharpe ratio and risk-adjusted return", "The Sharpe ratio is mean excess return divided by the standard deviation of returns, annualized. A Sharpe of 1 is good for a single strategy; above 2 usually means high frequency, leverage, or overfitting. Sortino uses downside deviation only. Risk-adjusted return, not raw return, is what allows fair comparison and leverage decisions. Sharpe is unreliable for strategies with fat tails, like short volatility."),
    ("Diversification and correlation", "Diversification across uncorrelated strategies and markets is the only free lunch in finance: combining two strategies with Sharpe 0.5 and zero correlation gives a Sharpe around 0.7. Correlations rise in crises, so diversification fails exactly when needed unless it includes trend following or long volatility. Portfolio construction weights strategies by risk, not by capital."),
    ("Leverage and margin", "Leverage multiplies both returns and volatility. Because losses compound asymmetrically, a leveraged strategy with positive expectancy can still lose money through volatility drag. Margin calls force liquidation at the worst time. Leverage should be set by volatility targeting and Kelly logic, not by what the broker allows."),
    ("Transaction costs and slippage", "Transaction costs include commissions, the bid-ask spread, and slippage, the difference between the expected and the actual fill price. Market impact grows with order size relative to liquidity. Many backtested strategies, especially high-turnover mean reversion, are profitable before costs and losers after. Always model costs and prefer limit orders in liquid markets."),
    ("Backtesting", "Backtesting simulates a strategy on historical data. A trustworthy backtest uses point-in-time data, realistic costs and slippage, no look-ahead bias, and survivorship-bias-free universes. Report Sharpe, max drawdown, number of trades, turnover, and out-of-sample results. A backtest is evidence about the past, not a forecast, and its quality depends on how many strategies were tried before this one."),
    ("Overfitting and data snooping", "Overfitting means a strategy fits noise in the historical data rather than a real effect. Symptoms: many tuned parameters, spectacular in-sample Sharpe, collapse out of sample. Data snooping bias comes from testing many variants and reporting the best. Defenses: fewer parameters, economic rationale, walk-forward testing, and deflating the Sharpe ratio for the number of trials. Look-ahead bias, using information not available at the time, is the most common backtest bug."),
    ("Walk-forward and out-of-sample testing", "Walk-forward analysis optimizes parameters on one window, tests on the next, then rolls forward, so every test period is out of sample. Cross-validation with purging and embargo adapts this to overlapping financial data. A strategy whose out-of-sample performance is within about half of its in-sample performance is usually acceptable; one that collapses was overfit."),
    ("Statistical significance of trading results", "A strategy's track record must be long enough for its Sharpe ratio to be distinguishable from zero: the t-statistic is roughly Sharpe times the square root of years. Two years of Sharpe 1 gives t about 1.4, not significant. Hundreds of trades are needed to trust a win rate. Multiple testing across many strategies inflates false positives; the deflated Sharpe ratio corrects for this."),
    ("Survivorship bias", "Survivorship bias arises when backtests use only assets that still exist today, ignoring the delisted, bankrupt or merged ones. It inflates returns of stock-picking strategies, especially in small caps and crypto. Use point-in-time universes that include dead assets."),
    ("Market efficiency and anomalies", "The efficient market hypothesis says prices reflect available information, so no strategy should earn excess risk-adjusted return. Documented anomalies include momentum, value, low volatility, post-earnings announcement drift and short-term reversal. Many published anomalies shrink after publication as capital arbitrages them away, so edges decay and must be monitored."),
    ("Behavioral finance", "Behavioral finance explains anomalies through investor psychology: loss aversion makes traders hold losers and sell winners (the disposition effect), overconfidence causes over-trading, herding creates trends and bubbles, and anchoring ties expectations to past prices. Systematic rules exist largely to remove these biases from the trader's own decisions."),
    ("Factor investing", "Factors are persistent return drivers: market beta, size, value, momentum, quality, low volatility, and carry. Fama and French formalized the framework. A strategy's alpha is its return not explained by factor exposures. Many 'unique' strategies are just factor exposures in disguise, so factor regression is a standard due-diligence step."),
    ("Pairs trading and statistical arbitrage", "Pairs trading goes long one asset and short a related one when their spread deviates from its historical relationship, betting on convergence. Cointegration tests identify pairs whose spread is stationary. Statistical arbitrage generalizes this to portfolios of many small mean reverting bets. Risks: the relationship breaks (a structural change), and crowded unwinds like August 2007."),
    ("Options and the Greeks", "Options give the right to buy (call) or sell (put) at a strike price. Their value depends on the underlying price (delta), the curvature (gamma), time decay (theta), and implied volatility (vega). Selling options harvests the volatility risk premium but has fat left tails; buying options loses to theta most of the time but pays in crashes. Implied volatility relative to realized volatility is the core options trading signal."),
    ("Futures, contango and backwardation", "Futures are contracts to trade an asset at a future date. The term structure is in contango when later contracts are pricier than nearer ones, and in backwardation when cheaper. Rolling long positions in contango costs money (negative roll yield); backwardation earns it. Carry strategies trade this systematically across commodities, currencies and rates."),
    ("Forex and the carry trade", "Forex is traded in pairs; the quote is the price of the base currency in the quote currency. Drivers are interest rate differentials, growth, inflation and risk appetite. The carry trade borrows low-yielding currencies to buy high-yielding ones; it earns steadily and crashes in risk-off episodes. Trend following and carry are the two classic systematic forex strategies."),
    ("Crypto market structure", "Crypto trades 24/7 across many fragmented venues with high retail participation, which produces strong momentum, high volatility, frequent liquidation cascades and exploitable inefficiencies such as funding rate arbitrage. Regime shifts are violent. Survivorship bias is severe because most tokens go to zero. Risk management must account for exchange and custody risk."),
    ("Market microstructure and order flow", "Market microstructure studies how orders become prices: the limit order book, bid-ask spread, queue priority and market maker behavior. Order flow imbalance predicts short-term price moves. High frequency trading exploits these effects at millisecond scale. For slower traders, microstructure matters through execution: when and how to place orders to minimize slippage."),
    ("Market making", "Market makers post bids and offers, earning the spread while managing inventory risk and adverse selection (trading against informed flow). Profit is spread minus adverse selection minus inventory cost. Quotes are skewed to unload inventory. Market making is high Sharpe in calm markets and loses badly in fast moves, which is why makers widen or pull quotes in volatility."),
    ("Macro drivers and interest rates", "Macro variables drive regimes: rising interest rates pressure long-duration assets like growth stocks and bonds, inflation surprises move rates and commodities, and central bank policy sets the risk-free rate against which everything is priced. Recessions bring correlated drawdowns. Macro data releases (payrolls, CPI, FOMC) cause volatility spikes that systematic traders often avoid or size down around."),
    ("Earnings and event-driven trading", "Earnings announcements create gaps and volatility. Post-earnings announcement drift is the tendency of prices to keep moving in the direction of the surprise for weeks. Options implied moves around earnings are often larger than realized moves, which sellers exploit. Holding positions through earnings is a discrete risk that position sizing must account for."),
    ("Fundamental analysis and valuation", "Fundamental analysis values assets from cash flows, earnings, book value, growth and quality. Value investing buys cheap on measures like price to earnings or price to book. Fundamentals drive long-horizon returns; technicals dominate short horizons. Combining a fundamental filter with technical timing is a common hybrid."),
    ("Technical analysis", "Technical analysis studies price and volume to forecast direction, assuming that prices discount everything and that patterns repeat because of human behavior. Tools include trend lines, support and resistance, moving averages, oscillators like RSI and MACD, and volume analysis. Systematic tests show that trend and momentum components of technical analysis have real edge; most discretionary pattern reading does not."),
    ("Algorithmic and systematic trading", "Systematic trading turns rules into code: data ingestion, signal generation, portfolio construction, risk limits and execution. Its advantages are discipline, testability and scale; its risks are model error, overfitting and technology failure. A trading system needs monitoring for signal decay, since edges erode as others discover them."),
    ("Machine learning in trading", "Machine learning finds patterns in features such as returns, volatility, order flow and text sentiment. Financial data is noisy, non-stationary and small, so overfitting is the central danger. Best practice: simple models, strong regularization, purged cross-validation, feature importance checks, and economic rationale. Deep learning and reinforcement learning show promise mainly in execution and in high-frequency contexts with abundant data."),
    ("News and sentiment", "Sentiment from news, social media and analyst tone predicts short-term returns, especially for retail-heavy assets and around events. Sentiment signals decay within hours to days. Extreme sentiment is contrarian: euphoria precedes tops, capitulation precedes bottoms. Natural language models turn text into scores that feed systematic strategies."),
    ("Portfolio optimization and risk parity", "Mean-variance optimization (Markowitz) finds the portfolio with the best return for a given risk, but it is hypersensitive to estimation error in expected returns. Risk parity sidesteps this by weighting assets so each contributes equal risk, usually leveraging bonds. Practical approaches shrink estimates, cap weights and rebalance on volatility."),
    ("Tail risk and fat tails", "Financial returns have fat tails: extreme moves happen far more often than a normal distribution predicts. Sharpe ratio and volatility understate tail risk, especially for strategies that sell options or provide liquidity. Tail hedges (long puts, trend following, long volatility) cost carry but pay in crashes. Sizing for the tail, not the average day, is what keeps traders alive through black swans."),
    ("Seasonality and calendar effects", "Calendar effects include the turn-of-the-month effect, the January effect in small caps, weaker returns in September, and intraday patterns like the opening range and the close. Many are small and have faded since publication. Seasonality is best used as a mild tilt on top of stronger signals, never as a standalone strategy."),
    ("Hedging", "Hedging reduces risk by taking an offsetting position: shorting index futures against a stock portfolio, buying puts, or pairing longs with shorts. Hedges cost money (premium, carry, or foregone upside), so the decision is whether the risk reduction is worth the drag. Beta hedging isolates alpha; tail hedging protects against crashes."),
    ("Trading psychology and discipline", "Most trader failures are behavioral: revenge trading after a loss, oversizing after a win, moving stops, and abandoning a system during its drawdown. Discipline comes from predefined rules, position sizing that keeps any single loss survivable, and reviewing a trading journal. Systematic traders automate to remove themselves from the moment of decision."),
]


def all_titles() -> list[str]:
    from bigbrain.knowledge import all_lessons

    return [t for t, _ in CURRICULUM] + [t for _, t, _ in all_lessons()]


def seed(brain: Brain, packs: bool = True) -> int:
    """Teach the curriculum and every knowledge pack. Returns the number of new cells created."""
    before = brain.count_cells()
    for title, text in CURRICULUM:
        brain.learn("concept", title, text, source="bigbrain curriculum")
    if packs:
        from bigbrain.knowledge import all_lessons

        for domain, title, text in all_lessons():
            brain.learn("concept", title, text, source=f"bigbrain knowledge: {domain}")
    return brain.count_cells() - before
